import type { Metadata } from "next";
import { cookies } from "next/headers";
import { BadgeDollarSign, Clock3, CreditCard, Users } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import SiteHeader from "../components/site-header";
import SiteFooter from "../components/site-footer";
import { COOKIE_NAME, readAffiliateSession } from "../lib/affiliate-auth";
import { db, ensureAffiliateSchema } from "../lib/affiliate-db";
import AffiliateLoginForm from "./login-form";
import LogoutButton from "./logout-button";

export const metadata:Metadata={title:"Creator Dashboard | Darth Algo",robots:{index:false,follow:false}};
const money=(cents:number,currency="usd")=>new Intl.NumberFormat("en-US",{style:"currency",currency:currency.toUpperCase()}).format(cents/100);
type AffiliateRow={id:string;full_name:string;status:string;preferred_code:string;commission_rate_bps:number;approved_at:Date|null};
type TotalsRow={sales:number;revenue:number;holding:number;payable:number;paid:number};
type CommissionRow={created_at:Date;gross_cents:number;commission_cents:number;currency:string;status:string};

export default async function AffiliateDashboard(){
  let id:null|string=null; try{id=readAffiliateSession((await cookies()).get(COOKIE_NAME)?.value);}catch{}
  let affiliate:AffiliateRow|null=null; let totals:TotalsRow|null=null; let recent:CommissionRow[]=[];
  if(id){try{await ensureAffiliateSchema();[affiliate]=await db()<AffiliateRow[]>`select id,full_name,status,preferred_code,commission_rate_bps,approved_at from affiliate_applications where id=${id}`;if(affiliate){await db()`update affiliate_commissions set status='payable' where affiliate_id=${id} and status='holding' and payable_at<=now()`;[totals]=await db()<TotalsRow[]>`select count(*)::int sales,coalesce(sum(gross_cents),0)::int revenue,coalesce(sum(commission_cents) filter(where status='holding'),0)::int holding,coalesce(sum(commission_cents) filter(where status='payable'),0)::int payable,coalesce(sum(commission_cents) filter(where status='paid'),0)::int paid from affiliate_commissions where affiliate_id=${id}`;recent=await db()<CommissionRow[]>`select created_at,gross_cents,commission_cents,currency,status from affiliate_commissions where affiliate_id=${id} order by created_at desc limit 20`;}}catch{affiliate=null;}}
  const cards:Array<[LucideIcon,string,string|number]>=[[Users,'New customers',totals?.sales??0],[CreditCard,'First-purchase revenue',money(totals?.revenue??0)],[Clock3,'Pending commission',money(totals?.holding??0)],[BadgeDollarSign,'Ready / paid',`${money(totals?.payable??0)} / ${money(totals?.paid??0)}`]];
  return <div className="min-h-screen bg-[#0d1117] text-white"><SiteHeader/><main className="section-shell py-14">{!affiliate?<AffiliateLoginForm/>:<><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.2em] text-ember">Darth Algo Creator</p><h1 className="mt-2 text-3xl font-black">Welcome, {affiliate.full_name}</h1><p className="mt-2 text-sm text-zinc-400">Status: <span className="font-black uppercase text-white">{affiliate.status}</span></p></div><LogoutButton/></div>{affiliate.status==='pending'?<div className="mt-10 rounded-xl border border-amber-300/20 bg-amber-300/[.06] p-7"><Clock3 className="h-7 w-7 text-amber-300"/><h2 className="mt-4 text-xl font-black">Application under review</h2><p className="mt-2 max-w-2xl leading-7 text-zinc-400">Your dashboard is ready. Once approved, your Stripe code and earnings reporting will activate here.</p></div>:<><div className="mt-10 rounded-xl border border-emerald-300/20 bg-emerald-300/[.06] p-6"><p className="text-sm font-bold text-emerald-200">Your active creator code</p><p className="mt-2 text-3xl font-black tracking-widest">{affiliate.preferred_code}</p><p className="mt-2 text-sm text-zinc-400">Share this code with your audience for use at Darth Algo checkout. Commission is earned once, on each new customer&apos;s first paid purchase—not on renewals.</p></div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([Icon,label,value])=><div key={label} className="rounded-xl border border-white/10 bg-[#111720] p-5"><Icon className="h-5 w-5 text-ember"/><p className="mt-4 text-sm text-zinc-500">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>)}</div><div className="mt-8 overflow-hidden rounded-xl border border-white/10"><div className="border-b border-white/10 bg-white/[.03] px-5 py-4 font-black">Recent first-purchase commissions</div>{recent.length===0?<p className="p-6 text-sm text-zinc-500">No tracked customers yet. A new customer&apos;s first qualified purchase will appear here.</p>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-black/20 text-zinc-500"><tr><th className="p-4">Date</th><th className="p-4">First purchase</th><th className="p-4">Commission</th><th className="p-4">Status</th></tr></thead><tbody>{recent.map((row)=><tr key={row.created_at.toISOString()} className="border-t border-white/10"><td className="p-4">{row.created_at.toLocaleDateString()}</td><td className="p-4">{money(row.gross_cents,row.currency)}</td><td className="p-4 font-bold">{money(row.commission_cents,row.currency)}</td><td className="p-4 uppercase text-zinc-400">{row.status}</td></tr>)}</tbody></table></div>}</div></>}</>}</main><SiteFooter/></div>;
}
