"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
type Connection={connected:boolean;dailyCreditCap:number;latest:null|{status:string;balance:null|{totalCredits:number;renewableResetsAt:string|null};checked_at:string}};
const labels:Record<string,string>={waiting_for_credits:"Waiting for research credits",observed_posts:"Social posts collected",checking:"Checking connection",reserved:"Research in progress",connection_failed:"Sign-in needs checking",tools_unavailable:"Provider tools unavailable",balance_unverified:"Credit balance could not be verified",no_verified_posts:"No usable post links returned",provider_error:"Provider could not complete research",provider_outcome_unknown:"Result uncertain — held until tomorrow",paused_or_disconnected:"Research paused"};
export default function Connections(){
 const [data,setData]=useState<Connection|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[locked,setLocked]=useState(false);
 async function refresh(){try{const r=await fetch("/api/owner/connections/vidiq",{cache:"no-store"});if(r.status===401){setLocked(true);return;}if(!r.ok)throw Error();setData(await r.json());setLocked(false);}catch{setMessage("Connection status is temporarily unavailable. Refresh to try again.");}}
 useEffect(()=>{void refresh();if(new URLSearchParams(location.search).get("vidiq")==="sign_in_failed")setMessage("The sign-in did not finish. Use Connect vidIQ to start again.");},[]);
 async function change(method:"POST"|"DELETE"){setBusy(true);setMessage("");try{const r=await fetch("/api/owner/connections/vidiq",{method});const body=await r.json();if(!r.ok)throw Error(body.error||"Connection unavailable");if(method==="POST"){location.assign(body.url);return;}await refresh();setMessage("Disconnected. Server research will no longer use this account.");}catch(e){setMessage(e instanceof Error?e.message:"Please try again.");}finally{setBusy(false);}}
 const button="rounded-xl bg-violet-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50";
 return <main className="mx-auto min-h-screen max-w-4xl px-6 py-16 text-white"><Link href="/owner" className="text-sm text-violet-300">← AI Command Center</Link><p className="mt-10 text-xs uppercase tracking-widest text-violet-300">Darth Algo · Private workspace</p><h1 className="mt-3 text-4xl font-semibold">Connect your agents</h1><p className="mt-4 max-w-2xl text-slate-300">One-time connections let your agents keep working when your computer is off.</p>
 {message&&<p role="status" className="mt-6 rounded-xl border border-violet-400/30 p-4">{message}</p>}
 {locked?<section className="mt-8 rounded-2xl border border-white/10 bg-white/5 p-7"><h2 className="text-xl font-semibold">Open your private Command Center first</h2><p className="my-4 text-slate-300">Use your existing owner sign-in, then return here to connect research.</p><Link className={button} href="/owner">Open owner sign-in</Link></section>:<section className="mt-8 rounded-2xl border border-white/10 bg-white/5 p-7"><p className="text-sm text-violet-300">Research + Growth → Indicator Builder</p><h2 className="mt-2 text-2xl font-semibold">Find what traders need</h2><p className="mt-3 text-slate-300">Discover public Instagram and TikTok posts through vidIQ. Agents look for indicator ideas, repeated frustrations and useful trading setups, then pass supported ideas to the builder. YouTube and TradingView research continue separately.</p><p className="mt-5 font-medium">{!data?"Checking connection…":!data.connected?"Needs one-time vidIQ sign-in":data.latest?labels[data.latest.status]||"Waiting for next scheduled check":"Connected · First scheduled check pending"}</p>{data?.connected&&data.latest?.balance&&<p className="mt-2 text-sm text-slate-300">{data.latest.balance.totalCredits} research credits at last check{data.latest.balance.renewableResetsAt?` · Renewal: ${new Date(data.latest.balance.renewableResetsAt).toLocaleDateString()}`:""}</p>}<p className="mt-3 text-sm text-slate-400">Up to 5 credits per day. No automatic purchases. Coverage depends on the provider’s available results; TikTok support still needs a live result check.</p><div className="mt-6 flex flex-wrap gap-3"><button className={button} disabled={busy||!data} onClick={()=>void change("POST")}>{data?.connected?"Reconnect vidIQ":"Connect vidIQ"}</button>{data?.connected&&<button className="rounded-xl border border-white/20 px-5 py-3 text-sm" disabled={busy} onClick={()=>void change("DELETE")}>Disconnect</button>}<button className="px-4 py-3 text-sm text-violet-300" disabled={busy} onClick={()=>void refresh()}>Refresh status</button></div></section>}
 <section className="mt-6 rounded-2xl border border-white/10 p-7"><p className="text-sm text-amber-300">Still needs a hosted browser connection</p><h2 className="mt-2 text-2xl font-semibold">TradingView private tests</h2><p className="mt-3 text-slate-300">Your current private preview works in your signed-in browser. Daily unattended testing, chart screenshots and approved publishing still need a server browser signed into TradingView. That worker is not running yet.</p><p className="mt-3 text-sm text-slate-400">Indicator packages remain held until real chart testing and the educational example are complete. Each finished package still needs your approval before publishing.</p></section></main>;
}
