export const verifiedAt='2026-09-23T03:14:00Z';
export const capabilityInventory=[
 {platform:'instagram',account:'@darth.algo (owner supplied; messaging identity unverified)',provider:'Manychat preferred',trigger:'Eligible Follow-to-DM → non-URL opt-in → offer; otherwise inbound WELCOME',permissions:'Unified Instagram onboarding and provider messaging access',eligibility:'Meta-selected beta; plan purchase does not unlock it. Account inspection requires sign-in.',restrictions:'Once per follower; one Follow-to-DM per recipient per week across participating accounts; 24-hour conversation window after reply/opt-in. No link-only opener.',cost:'Account plan/usage unavailable; beta documented on Free and Pro. No paid plan started.',blocker:'Instagram authorization from Manychat onboarding and account eligibility test; discount duration mismatch',verifiedAt},
 {platform:'x',account:'Messaging account not verified',provider:'X API (not connected)',trigger:'Inbound WELCOME or another explicit request for this offer',permissions:'User-context DM read/write authorization and approved event subscription',eligibility:'Developer console sign-in, app scopes and credits unverified',restrictions:'Following/open DMs/old conversation is not promotional opt-in. STOP suppresses; no reminders.',cost:'Official list: DM received/read $0.010; DM create $0.015. Account rate/credits unavailable; $0.025 per inbound+reply estimate excludes extras.',blocker:'X developer sign-in, scopes, explicit spending approval if existing credits unavailable',verifiedAt},
 {platform:'tiktok',account:'Business account/region not verified',provider:'TikTok native preferred',trigger:'User starts chat or sends exact WELCOME keyword; not follower-triggered',permissions:'Advanced Access and Verified Business Account; messages from Everyone',eligibility:'Business Center sign-in required; region and commercial-content eligibility unverified',restrictions:'Welcome 250 characters, keyword reply 500, keyword 40; moderation 1–5 business days. STOP behavior must be tested before activation.',cost:'No purchase made; account-specific native/provider cost unavailable',blocker:'Verified business/region inspection, message moderation and opt-out test',verifiedAt}
];
export const ownerActions=[
 'WELCOME replacement terms approved on September 23: 25% off once for first-time customers, no product exclusions or expiry, and no global redemption cap. Stripe sandbox validation is still required before the live replacement.',
 'Complete Instagram authorization from the Manychat channel setup screen for @darth.algo; account eligibility and existing free capacity still need verification.',
 'Connect the X developer account and TikTok Business Center; any additional spend or new permissions will be presented before activation.',
 'Connect a Stripe test environment for checkout and trial-to-paid verification; select an owner-controlled messaging test recipient after provider connection.'
];
