'use client';
import {useCallback,useEffect,useRef,useState,type ReactNode} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {Activity,ArrowUpRight,Bot,ChevronRight,House,Inbox,RefreshCw,Send,Wallet,Wrench,X} from 'lucide-react';
import type {CeoHome} from '../lib/business-os/ceo-home';
import FinanceChart from './finance-chart';
import VideoStudio from './video-studio';
import DailyContentQueue from './daily-content-queue';
import {VisualTeam,AgentPanel,type AgentMode} from './visual-team';
import visual from './visual-hq.module.css';
import {ownerViewFromSearch,ownerViewParam,type OwnerView} from './video-studio-model';
import mobile from './video-studio.module.css';
import {agentHealth,systemHealth,monthlyCents,type Bill,type Health} from '../lib/business-os/ceo-home-model';
import styles from './business-home.module.css';
const money=(cents:number|null|undefined)=>cents==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
const time=(date:string|null|undefined)=>date?new Date(date).toLocaleString('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})+' ET':'Not yet recorded';
function Rating({health}:{health:Health}){return <span className={`${styles.rating} ${styles[health.rating.toLowerCase()]}`}>{health.rating}</span>;}
export default function BusinessHome({workspace}:{workspace:ReactNode}){
 const [view,setView]=useState<OwnerView>('home');
 const [agentMode,setAgentMode]=useState<AgentMode>('work'),[studioOpen,setStudioOpen]=useState(false);
 const openAgent=(id:string,mode:AgentMode='work')=>{setSelected(id);setAgentMode(mode);};
 const [refreshing,setRefreshing]=useState(false),[offline,setOffline]=useState(false);
 const navigate=(next:OwnerView)=>{setView(next);const url=new URL(window.location.href);url.searchParams.set('view',next==='queue'?'queue':ownerViewParam(next));url.hash='';window.history.pushState(window.history.state,'',url);window.scrollTo({top:0,behavior:'auto'});requestAnimationFrame(()=>document.getElementById('hq-heading')?.focus({preventScroll:true}));};
 const [data,setData]=useState<CeoHome|null>(null),[authorized,setAuthorized]=useState<boolean|null>(null),[controls,setControls]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[pending,setPending]=useState(''),[selected,setSelected]=useState<string|null>(null),[bill,setBill]=useState<Bill|null>(null),[clock,setClock]=useState(Date.now());
 const reading=useRef(false),request=useRef<AbortController|null>(null),mutating=useRef(false);
 const hasDialog=Boolean(selected||bill);
 const refresh=useCallback(async()=>{
  if(reading.current)return;reading.current=true;setRefreshing(true);const controller=new AbortController();request.current=controller;const timeout=setTimeout(()=>controller.abort(),30000);
  try{const r=await fetch('/api/owner/dashboard',{cache:'no-store',credentials:'same-origin',signal:controller.signal});if(r.status===401){setAuthorized(false);setData(null);return;}if(!r.ok)throw Error('Live data could not be refreshed.');const d=await r.json();if(!d.checkedAt||!Array.isArray(d.team))throw Error('The status response could not be verified.');setData(d);setAuthorized(true);setError('');setClock(Date.now());}
  catch{setError('Live data could not be refreshed. Saved figures may be out of date.');}finally{clearTimeout(timeout);reading.current=false;setRefreshing(false);}
 },[]);
 useEffect(()=>{
  const read=()=>{setView(ownerViewFromSearch(window.location.search));setStudioOpen(new URLSearchParams(window.location.search).get('view')==='studio');setControls(false);setSelected(null);setBill(null);};
  const connection=()=>{setOffline(!navigator.onLine);if(navigator.onLine)void refresh();};
  const visible=()=>{if(document.visibilityState==='visible')void refresh();};
  read();setOffline(!navigator.onLine);window.addEventListener('popstate',read);window.addEventListener('online',connection);window.addEventListener('offline',connection);document.addEventListener('visibilitychange',visible);
  return()=>{window.removeEventListener('popstate',read);window.removeEventListener('online',connection);window.removeEventListener('offline',connection);document.removeEventListener('visibilitychange',visible);};
 },[refresh]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>{setClock(Date.now());if(document.visibilityState==='visible')void refresh();},30000);return()=>{clearInterval(timer);request.current?.abort();};},[refresh]);
 useEffect(()=>{
  if(!hasDialog)return;
  const priorOverflow=document.body.style.overflow;document.body.style.overflow='hidden';
  const prior=document.activeElement as HTMLElement|null,dialog=document.querySelector<HTMLElement>('[role="dialog"]');
  const focusable=()=>Array.from(dialog?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input,textarea,select,summary')||[]);
  focusable()[0]?.focus();
  const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){setSelected(null);setBill(null);}if(event.key==='Tab'){const items=focusable(),first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}};
  document.addEventListener('keydown',key);return()=>{document.body.style.overflow=priorOverflow;document.removeEventListener('keydown',key);prior?.focus();};
 },[hasDialog]);
 async function act(operation:string,body:Record<string,unknown>={}){
  if(mutating.current)return;mutating.current=true;setPending(operation);setNotice('');
  try{const r=await fetch('/api/owner/dashboard',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation,...body})});const d=await r.json();if(!r.ok)throw Error(d.error||'The change was not confirmed.');setNotice(d.message||'Saved.');if(operation==='bill')setBill(null);await refresh();}
  catch(e){setNotice(e instanceof Error?e.message:'The request was not confirmed. Refresh before trying again.');}finally{mutating.current=false;setPending('');}
 }
 if(authorized===false)return <>{workspace}</>;
 if(controls)return <><div className={styles.back}><button onClick={()=>{setControls(false);void refresh();}}>← Back to home</button></div>{workspace}</>;
 if(!data)return <main className={styles.shell}><div className={styles.loading}><Activity/><h1>{error?'Your dashboard needs a fresh check':'Opening your business'}</h1><p>{error||'Reading your financial and agent records.'}</p>{error&&<button onClick={()=>void refresh()}>Try again</button>}</div></main>;
 const stale=offline||Boolean(error)||clock-Date.parse(data.checkedAt)>75000;
 const team=data.team.map(a=>({...a,health:stale?{rating:'Unknown',reason:'Live status is out of date.'} as Health:data.desk?agentHealth(a,data.desk,data.issues,clock):a.health}));
 const health=stale?{rating:'Unknown',reason:'Refresh required before this status can be trusted.'} as Health:systemHealth(team.map(a=>a.health),data.desk,data.issues,data.partial);
 const agent=team.find(a=>a.id===selected),f=data.finances;
 const needs=data.issues.filter(i=>i.needsOwner),done=team.filter(a=>a.completed).sort((a,b)=>Date.parse(b.completed!.finishedAt||'')-Date.parse(a.completed!.finishedAt||'')).slice(0,4);
 return <main className={`${styles.shell} ${mobile.mobile} ${visual.uniform}`} id='home'><div className={styles.wrap} inert={hasDialog}>
  <header className={styles.header}><div className={styles.brand}><Image src='/darth-algo-social-logo.png' width={44} height={44} alt='Darth Algo'/><div><strong>DARTH ALGO</strong><span>BUSINESS HEADQUARTERS</span></div></div><div className={visual.headerActions}><button className={styles.icon} aria-label={refreshing?'Refreshing dashboard':'Refresh dashboard'} disabled={refreshing||offline} onClick={()=>void refresh()}><RefreshCw size={19} className={refreshing?mobile.refreshing:undefined}/></button><button className={styles.icon} aria-label='More controls' onClick={()=>setControls(true)}><Inbox size={19}/></button></div></header>
  <div className={styles.intro}><div><p className={styles.eyebrow}>YOUR COMPANY. IN YOUR HANDS.</p><h1 id='hq-heading' tabIndex={-1}>{view==='home'?'Headquarters':view==='team'?'Your team':view==='queue'?'Content queue':'Money overview'}</h1></div><span className={styles.updated}>{stale?'Update unavailable':time(data.checkedAt)}</span></div>
  {offline&&<p role='status' className={styles.alert}>You are offline. Saved figures may be out of date; new work is disabled until you reconnect.</p>}
  {error&&<p role='alert' className={styles.alert}>{error}</p>}{notice&&<p role='status' className={styles.notice}>{notice}</p>}
  {(view==='home'||view==='bills')&&<FinanceChart finances={f}/>}
  {view==='home'&&<div className={mobile.shortcuts} aria-label='Quick actions'><button onClick={()=>{navigate('queue');setStudioOpen(true);}}><Send size={20}/><strong>Create a video</strong><small>Storyboard & content queue</small></button><button onClick={()=>navigate('team')}><Bot size={20}/><strong>Open your team</strong><small>{team.length} registered agents</small></button><button onClick={()=>navigate('bills')}><Wallet size={20}/><strong>Review money</strong><small>Income, customers & bills</small></button></div>}
  <div hidden={view!=='queue'}><DailyContentQueue active={view==='queue'} disabled={stale} onOpenAgent={()=>openAgent('content','message')}/><details className={visual.videoDrawer} open={studioOpen} onToggle={e=>setStudioOpen(e.currentTarget.open)}><summary>Create a video</summary><VideoStudio active={view==='queue'&&studioOpen} disabled={stale} onOpenTeam={()=>{navigate('team');openAgent('content','assign');}}/></details></div>
  <section hidden={view!=='home'&&view!=='bills'} className={styles.metrics} aria-label='Company finances'>
   <article><Wallet size={18}/><span>Income · last 30 days</span><strong>{money(f?.income.incomeCents)}</strong><small>Stripe payments · before costs</small></article>
   <article><Bot size={18}/><span>Current customers</span><strong>{f?.customers.active??'—'}</strong><small>Active Stripe subscribers{f?.customers.trials!=null?` · ${f.customers.trials} trials`:''}</small></article>
   <article><Wallet size={18}/><span>Monthly bill budget</span><strong>{money(f?.expenses.monthlyCents)}</strong><small>{f?`${f.expenses.estimated} estimated · ${f.expenses.missing} missing`:'Records unavailable'}</small></article>
   <article><Activity size={18}/><span>Bills / income</span><strong>{f?.expenses.ratio!=null?`${f.expenses.ratio.toFixed(1)}%`:'—'}</strong><small>{f?.expenses.complete?'Monthly bills ÷ 30-day income':f?.expenses.estimated?'Estimated costs ÷ 30-day income':'Incomplete cost coverage'}</small></article>
  </section>
  <details hidden={view!=='home'&&view!=='bills'} className={styles.definitions}><summary>Sources & estimates</summary><p>{f?.income.scope||'Financial records could not be read.'} {f?.customers.scope} Bills are monthly equivalents; annual bills are divided by 12. Bills/income measures operating costs, not personal debt-to-income. This is not net profit.</p>{Boolean(f?.income.otherCurrencies.length)&&<p>Excluded currencies: {f?.income.otherCurrencies.join(', ').toUpperCase()}. No currency conversion is applied.</p>}<p>Income checked {time(f?.income.checkedAt)}. Customer count checked {time(f?.customers.checkedAt)}. {f?.billSync}</p></details>
  <section hidden={view!=='home'} className={styles.healthCard} aria-label='System health'><div className={styles.heading}><div><p className={styles.eyebrow}>SYSTEM HEALTH</p><h2>{health.rating==='Great'?'Everything is moving.':health.rating==='Good'?'Moving. With a few loose ends.':health.rating==='Poor'?'Your team needs a hand.':'Checking your business.'}</h2></div><Rating health={health}/></div><div className={styles.meter} role='img' aria-label={`System health: ${health.rating}`}><span className={health.rating==='Poor'?styles.meterPoor:''}>Poor</span><span className={health.rating==='Good'?styles.meterGood:''}>Good</span><span className={health.rating==='Great'?styles.meterGreat:''}>Great</span></div><p>{health.reason}</p><div className={styles.row}><small>{data.desk?.counts.completedToday??'—'} completed today · {data.desk?.counts.queued??'—'} queued</small><button className={styles.primary} disabled={Boolean(pending)||stale} onClick={()=>void act('recover')}><Wrench size={16}/>{pending==='recover'?'Requesting recovery…':'Fix agents'}</button></div><small>Eligible recovery starts here. The maintenance watch checks for requests hourly.</small></section>
  <div hidden={view!=='home'} className={styles.columns}>
   <section className={styles.card} id='briefing'><div className={styles.heading}><h2>CEO briefing</h2><Inbox size={19}/></div><p className={styles.muted}>Latest completed work</p>{done.length?done.map(a=><button className={styles.briefRow} key={a.id} onClick={()=>openAgent(a.id)}><span><strong>{a.name}</strong><small>{a.completed?.brief?.slice(0,210)||'Internal work saved.'}</small><small>{time(a.completed?.finishedAt)}</small></span><ChevronRight size={18}/></button>):<p className={styles.muted}>No completed work is available yet.</p>}{data.brief&&<details className={styles.definitions}><summary>Read saved daily briefing</summary><p className={styles.pre}>{String(data.brief.body)}</p></details>}</section>
   <section className={styles.card} id='important'><div className={styles.heading}><h2>Needs your action</h2><span className={styles.count}>{needs.length}</span></div><p className={styles.muted}>Steps that require your access or decision</p>{needs.length?needs.map(i=><div className={styles.issue} key={i.id}><strong>{i.title}</strong><p>{i.reason}</p><Link href={i.href} onClick={e=>{if(i.href==='#team'||i.href==='#queue'||i.href==='#bills'){e.preventDefault();navigate(i.href==='#team'?'team':i.href==='#queue'?'queue':'bills');}}}>{i.action}<ArrowUpRight size={15}/></Link></div>):<p>No owner-only blockers were found in the available records.</p>}{data.partial.length>0&&<p className={styles.alert}>Some sources could not be read: {data.partial.join(', ')}. Health cannot be rated great until those checks succeed.</p>}<button className={styles.secondary} onClick={()=>setControls(true)}>Other decisions & controls <ChevronRight size={16}/></button></section>
  </div>
  <div hidden={view!=='team'} id='team'><VisualTeam team={team} fresh={!stale&&Boolean(data.desk)} now={clock} queue={data.queue} onOpen={openAgent}/></div>
  <section hidden={view!=='home'} className={styles.card} id='suggestions'><div className={styles.heading}><div><p className={styles.eyebrow}>FROM RESEARCH</p><h2>Ideas your agents can finish</h2></div><Bot size={21}/></div><p className={styles.muted}>Approve a specific deliverable. The assigned agent creates it and saves the result here within the current spending limits.</p>{!data.suggestions.length&&<p>Research has not saved an executable suggestion yet. New suggestions appear after its next completed review.</p>}{data.suggestions.map(s=><article className={styles.suggestion} key={s.id}><div className={styles.heading}><h3>{s.title}</h3><span className={styles.muted}>{s.state==='succeeded'?'Completed':s.state.replaceAll('_',' ')}</span></div><p>{s.deliverable}</p><details className={styles.definitions}><summary>Research behind this suggestion</summary><p className={styles.pre}>{s.sourceBrief}</p></details>{s.result&&<details open className={styles.definitions}><summary>Completed result</summary><p className={styles.pre}>{s.result}</p></details>}{s.error&&<p className={styles.alert}>{s.error.replaceAll('_',' ')}. Open the assigned agent for recovery.</p>}{s.state==='pending'&&<div className={styles.row}><button disabled={Boolean(pending)||stale} className={styles.primary} onClick={()=>void act('suggestion',{id:s.id,hash:s.hash,decision:'approved'})}>Approve & create</button><button disabled={Boolean(pending)||stale} className={styles.secondary} onClick={()=>void act('suggestion',{id:s.id,hash:s.hash,decision:'declined'})}>Decline</button></div>}</article>)}</section>
  <section hidden={view!=='bills'} className={styles.card} id='bills'><div className={styles.heading}><div><p className={styles.eyebrow}>OPERATING COSTS</p><h2>Company subscriptions</h2></div><button className={styles.secondary} disabled={!f} onClick={()=>setBill({id:'',name:'',amountCents:null,cadence:'monthly',status:'unverified',source:'',verifiedAt:null})}>Add bill</button></div><p className={styles.muted}>Your tools are prefilled. Estimates count toward the budget; tap any bill to see its basis or adjust it. Taxes, overages and unlisted tools may add to this total.</p>{f?.bills.map(b=><button key={b.id} className={styles.billRow} onClick={()=>setBill(b)}><span><strong>{b.name}</strong><small>{b.status==='inactive'?'Inactive':b.status==='unverified'?'Amount / active plan unverified':b.status==='estimated'?`Estimated · ${money(b.amountCents)} / ${b.cadence==='annual'?'year':b.cadence==='weekly'?'week':'month'}`:`${money(b.amountCents)} / ${b.cadence==='annual'?'year':b.cadence==='weekly'?'week':'month'}`}</small></span><span>{b.status==='confirmed'||b.status==='estimated'?`${money(monthlyCents(b))}/mo`:'—'}<ChevronRight size={15}/></span></button>)}</section>
  <footer className={styles.footer}>Private CEO view · Refreshes every 30 seconds while visible · Financial reads cached up to 15 minutes</footer>
 </div><nav className={styles.nav} aria-label='CEO navigation' inert={hasDialog}><button aria-current={view==='home'?'page':undefined} onClick={()=>navigate('home')}><House size={20}/>HQ</button><button aria-current={view==='team'?'page':undefined} onClick={()=>navigate('team')}><Bot size={20}/>Agents</button><button aria-current={view==='queue'?'page':undefined} onClick={()=>{navigate('queue');setStudioOpen(false);}}><Send size={20}/>Queue</button><button aria-current={view==='bills'?'page':undefined} onClick={()=>navigate('bills')}><Wallet size={20}/>Money</button></nav>
 {agent&&<div className={styles.overlay}><AgentPanel key={agent.id} agent={agent} mode={agentMode} onMode={setAgentMode} fresh={!stale&&Boolean(data.desk)} now={clock} issues={data.issues} onClose={()=>setSelected(null)} onChanged={()=>void refresh()}/></div>}
 {bill&&<div className={styles.overlay}><form className={styles.dialog} role='dialog' aria-modal='true' aria-labelledby='bill-title' onSubmit={e=>{e.preventDefault();void act('bill',{bill:{...bill,id:bill.id||bill.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,70)}});}}><div className={styles.heading}><h2 id='bill-title'>Company bill</h2><button className={styles.icon} type='button' aria-label='Close bill' onClick={()=>setBill(null)}><X/></button></div><label>Name<input required maxLength={100} value={bill.name} onChange={e=>setBill({...bill,name:e.target.value})}/></label><label>Charge in USD<input type='number' min='0' max='100000' step='0.01' value={bill.amountCents===null?'':bill.amountCents/100} onChange={e=>setBill({...bill,amountCents:e.target.value===''?null:Math.round(Number(e.target.value)*100)})}/></label><label>Billing cycle<select value={bill.cadence} onChange={e=>setBill({...bill,cadence:e.target.value as Bill['cadence']})}><option value='monthly'>Monthly</option><option value='annual'>Yearly</option><option value='weekly'>Weekly</option></select></label><label>Status<select value={bill.status} onChange={e=>setBill({...bill,status:e.target.value as Bill['status']})}><option value='estimated'>Estimated expense</option><option value='unverified'>Needs verification</option><option value='confirmed'>Confirmed company expense</option><option value='inactive'>Inactive / not a company expense</option></select></label><p className={styles.muted}>{bill.source}{bill.estimatedAt?` · Estimated ${time(bill.estimatedAt)}`:''}{bill.sourceUrl&&<> · <a href={bill.sourceUrl} target='_blank' rel='noreferrer'>Pricing source</a></>}</p><p className={styles.muted}>This updates your records. It does not change or cancel the provider subscription.</p>{notice&&<p role='status' className={styles.notice}>{notice}</p>}<button className={styles.primary} disabled={Boolean(pending)||stale}>Save bill</button></form></div>}
 </main>;
}
