'use client';
import {useCallback,useEffect,useRef,useState,type ReactNode} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {Activity,ArrowUpRight,Bot,ChevronRight,House,Inbox,RefreshCw,Send,Wallet,Wrench,X} from 'lucide-react';
import type {CeoHome} from '../lib/business-os/ceo-home';
import {agentHealth,systemHealth,monthlyCents,type Bill,type Health} from '../lib/business-os/ceo-home-model';
import styles from './business-home.module.css';
const money=(cents:number|null|undefined)=>cents==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
const time=(date:string|null|undefined)=>date?new Date(date).toLocaleString('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})+' ET':'Not yet recorded';
function Rating({health}:{health:Health}){return <span className={`${styles.rating} ${styles[health.rating.toLowerCase()]}`}>{health.rating}</span>;}
export default function BusinessHome({workspace}:{workspace:ReactNode}){
 const [data,setData]=useState<CeoHome|null>(null),[authorized,setAuthorized]=useState<boolean|null>(null),[controls,setControls]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[pending,setPending]=useState(''),[selected,setSelected]=useState<string|null>(null),[bill,setBill]=useState<Bill|null>(null),[clock,setClock]=useState(Date.now());
 const reading=useRef(false),request=useRef<AbortController|null>(null),mutating=useRef(false);
 const refresh=useCallback(async()=>{
  if(reading.current)return;reading.current=true;const controller=new AbortController();request.current=controller;const timeout=setTimeout(()=>controller.abort(),30000);
  try{const r=await fetch('/api/owner/dashboard',{cache:'no-store',credentials:'same-origin',signal:controller.signal});if(r.status===401){setAuthorized(false);setData(null);return;}if(!r.ok)throw Error('Live data could not be refreshed.');const d=await r.json();if(!d.checkedAt||!Array.isArray(d.team))throw Error('The status response could not be verified.');setData(d);setAuthorized(true);setError('');setClock(Date.now());}
  catch{setError('Live data could not be refreshed. Saved figures may be out of date.');}finally{clearTimeout(timeout);reading.current=false;}
 },[]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>{setClock(Date.now());if(document.visibilityState==='visible')void refresh();},30000);return()=>{clearInterval(timer);request.current?.abort();};},[refresh]);
 useEffect(()=>{
  if(!selected&&!bill)return;
  const prior=document.activeElement as HTMLElement|null,dialog=document.querySelector<HTMLElement>('[role="dialog"]');
  const focusable=()=>Array.from(dialog?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input,select,summary')||[]);
  focusable()[0]?.focus();
  const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){setSelected(null);setBill(null);}if(event.key==='Tab'){const items=focusable(),first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}};
  document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);prior?.focus();};
 },[selected,Boolean(bill)]);
 async function act(operation:string,body:Record<string,unknown>={}){
  if(mutating.current)return;mutating.current=true;setPending(operation);setNotice('');
  try{const r=await fetch('/api/owner/dashboard',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation,...body})});const d=await r.json();if(!r.ok)throw Error(d.error||'The change was not confirmed.');setNotice(d.message||'Saved.');if(operation==='bill')setBill(null);await refresh();}
  catch(e){setNotice(e instanceof Error?e.message:'The request was not confirmed. Refresh before trying again.');}finally{mutating.current=false;setPending('');}
 }
 if(authorized===false)return <>{workspace}</>;
 if(controls)return <><div className={styles.back}><button onClick={()=>{setControls(false);void refresh();}}>← Back to home</button></div>{workspace}</>;
 if(!data)return <main className={styles.shell}><div className={styles.loading}><Activity/><h1>{error?'Your dashboard needs a fresh check':'Opening your business'}</h1><p>{error||'Reading your financial and agent records.'}</p>{error&&<button onClick={()=>void refresh()}>Try again</button>}</div></main>;
 const stale=Boolean(error)||clock-Date.parse(data.checkedAt)>75000;
 const team=data.team.map(a=>({...a,health:stale?{rating:'Unknown',reason:'Live status is out of date.'} as Health:data.desk?agentHealth(a,data.desk,data.issues,clock):a.health}));
 const health=stale?{rating:'Unknown',reason:'Refresh required before this status can be trusted.'} as Health:systemHealth(team.map(a=>a.health),data.desk,data.issues,data.partial);
 const agent=team.find(a=>a.id===selected),f=data.finances;
 const needs=data.issues.filter(i=>i.needsOwner),done=team.filter(a=>a.completed).sort((a,b)=>Date.parse(b.completed!.finishedAt||'')-Date.parse(a.completed!.finishedAt||'')).slice(0,4);
 return <main className={styles.shell} id='home'><div className={styles.wrap}>
  <header className={styles.header}><div className={styles.brand}><Image src='/darth-algo-social-logo.png' width={44} height={44} alt='Darth Algo'/><div><strong>DARTH ALGO</strong><span>YOUR CEO DESK</span></div></div><button className={styles.icon} aria-label='Refresh dashboard' onClick={()=>void refresh()}><RefreshCw size={19}/></button></header>
  <div className={styles.intro}><div><p className={styles.eyebrow}>THE BUSINESS AT A GLANCE</p><h1>Your company.<br/><span>One clear view.</span></h1></div><span className={styles.updated}>{stale?'Update unavailable':time(data.checkedAt)}</span></div>
  {error&&<p role='alert' className={styles.alert}>{error}</p>}{notice&&<p role='status' className={styles.notice}>{notice}</p>}
  <section className={styles.metrics} aria-label='Company finances'>
   <article><Wallet size={18}/><span>Income · last 30 days</span><strong>{money(f?.income.incomeCents)}</strong><small>Stripe payments · before costs</small></article>
   <article><Bot size={18}/><span>Current customers</span><strong>{f?.customers.active??'—'}</strong><small>Active Stripe subscribers{f?.customers.trials!=null?` · ${f.customers.trials} trials`:''}</small></article>
   <article><Wallet size={18}/><span>Company bills / month</span><strong>{money(f?.expenses.monthlyCents)}</strong><small>{f?.expenses.complete?'Recorded recurring total':`${f?.expenses.missing??'Some'} bills unverified · partial subtotal`}</small></article>
   <article><Activity size={18}/><span>Bills / income</span><strong>{f?.expenses.ratio!=null?`${f.expenses.ratio.toFixed(1)}%`:'—'}</strong><small>{f?.expenses.complete?'Monthly bills ÷ 30-day gross income':'Known bills only · incomplete ratio'}</small></article>
  </section>
  <details className={styles.definitions}><summary>What these numbers include</summary><p>{f?.income.scope||'Financial records could not be read.'} {f?.customers.scope} Bills are monthly equivalents; annual bills are divided by 12. Bills/income measures operating costs, not personal debt-to-income. This is not net profit.</p><p>Income checked {time(f?.income.checkedAt)}. Customer count checked {time(f?.customers.checkedAt)}. {f?.billSync}</p></details>
  <section className={styles.healthCard} aria-label='System health'><div className={styles.heading}><div><p className={styles.eyebrow}>SYSTEM HEALTH</p><h2>Your business is {health.rating.toLowerCase()}.</h2></div><Rating health={health}/></div><div className={styles.meter} role='img' aria-label={`System health: ${health.rating}`}><span className={health.rating==='Poor'?styles.meterPoor:''}>Poor</span><span className={health.rating==='Good'?styles.meterGood:''}>Good</span><span className={health.rating==='Great'?styles.meterGreat:''}>Great</span></div><p>{health.reason}</p><div className={styles.row}><small>{data.desk?.counts.completedToday??'—'} internal requests completed today · {data.desk?.counts.queued??'—'} queued</small><button className={styles.primary} disabled={Boolean(pending)||stale} onClick={()=>void act('recover')}><Wrench size={16}/>{pending==='recover'?'Requesting recovery…':'Fix agents'}</button></div><small>Starts eligible recovery work and records a request for the hourly maintenance watch. Results appear in Operations.</small></section>
  <div className={styles.columns}>
   <section className={styles.card} id='briefing'><div className={styles.heading}><h2>CEO briefing</h2><Inbox size={19}/></div><p className={styles.muted}>Latest completed work</p>{done.length?done.map(a=><button className={styles.briefRow} key={a.id} onClick={()=>setSelected(a.id)}><span><strong>{a.name}</strong><small>{a.completed?.brief?.slice(0,210)||'Internal work saved.'}</small><small>{time(a.completed?.finishedAt)}</small></span><ChevronRight size={18}/></button>):<p className={styles.muted}>No completed work is available yet.</p>}{data.brief&&<details className={styles.definitions}><summary>Read saved daily briefing</summary><p className={styles.pre}>{String(data.brief.body)}</p></details>}</section>
   <section className={styles.card} id='important'><div className={styles.heading}><h2>Needs your action</h2><span className={styles.count}>{needs.length}</span></div><p className={styles.muted}>Steps that require your access or decision</p>{needs.length?needs.map(i=><div className={styles.issue} key={i.id}><strong>{i.title}</strong><p>{i.reason}</p><Link href={i.href}>{i.action}<ArrowUpRight size={15}/></Link></div>):<p>No owner-only blockers were found in the available records.</p>}{data.partial.length>0&&<p className={styles.alert}>Some sources could not be read: {data.partial.join(', ')}. Health cannot be rated great until those checks succeed.</p>}<button className={styles.secondary} onClick={()=>setControls(true)}>Other decisions & controls <ChevronRight size={16}/></button></section>
  </div>
  <section id='team' className={styles.section}><div className={styles.heading}><div><p className={styles.eyebrow}>YOUR TEAM</p><h2>Every agent. Every update.</h2></div><span className={styles.muted}>{team.length} agents</span></div><div className={styles.agentGrid}>{team.map(a=><button className={styles.agentCard} key={a.id} onClick={()=>setSelected(a.id)}><div className={styles.heading}><span className={styles.agentIcon}><Bot size={20}/></span><Rating health={a.health}/></div><h3>{a.name}</h3><p>{a.health.reason}</p><small>{a.current?'Working: '+a.current.message.slice(0,105):a.next?'Next: '+a.next.message.slice(0,105):'Last completed: '+time(a.completed?.finishedAt)}</small><span className={styles.open}>Open agent <ChevronRight size={15}/></span></button>)}</div></section>
  <section className={styles.card} id='suggestions'><div className={styles.heading}><div><p className={styles.eyebrow}>FROM RESEARCH</p><h2>Ideas your agents can finish</h2></div><Bot size={21}/></div><p className={styles.muted}>Approve a specific deliverable. The assigned agent creates it and saves the result here within the current spending limits.</p>{!data.suggestions.length&&<p>Research has not saved an executable suggestion yet. New suggestions appear after its next completed review.</p>}{data.suggestions.map(s=><article className={styles.suggestion} key={s.id}><div className={styles.heading}><h3>{s.title}</h3><span className={styles.muted}>{s.state==='succeeded'?'Completed':s.state.replaceAll('_',' ')}</span></div><p>{s.deliverable}</p><details className={styles.definitions}><summary>Research behind this suggestion</summary><p className={styles.pre}>{s.sourceBrief}</p></details>{s.result&&<details open className={styles.definitions}><summary>Completed result</summary><p className={styles.pre}>{s.result}</p></details>}{s.error&&<p className={styles.alert}>{s.error.replaceAll('_',' ')}. Open the assigned agent for recovery.</p>}{s.state==='pending'&&<div className={styles.row}><button disabled={Boolean(pending)||stale} className={styles.primary} onClick={()=>void act('suggestion',{id:s.id,hash:s.hash,decision:'approved'})}>Approve & create</button><button disabled={Boolean(pending)||stale} className={styles.secondary} onClick={()=>void act('suggestion',{id:s.id,hash:s.hash,decision:'declined'})}>Decline</button></div>}</article>)}</section>
  <section id='queue' className={styles.section}><div className={styles.heading}><div><p className={styles.eyebrow}>UP NEXT</p><h2>Your content queue</h2></div><Send size={20}/></div><p className={styles.muted}>9 AM and 3 PM Eastern · Instagram, X and Threads. Delivery still depends on the publishing checks.</p><div className={styles.queueGrid}>{data.queue.map(c=><article className={styles.post} key={c.id}>{c.image&&<Image src={c.image} alt={`Queued ${c.kind} artwork`} width={1080} height={1350} unoptimized/>}<div><span className={styles.eyebrow}>{c.kind}</span><h3>{c.day} · {c.slot==='morning'?'9 AM':'3 PM'} ET</h3><span className={styles.muted}>{c.state}</span><p>{c.text}</p></div></article>)}</div>{!data.queue.length&&<p>No reviewed upcoming campaign is available. Content needs to prepare the next slot.</p>}</section>
  <section className={styles.card} id='bills'><div className={styles.heading}><div><p className={styles.eyebrow}>OPERATING COSTS</p><h2>Company subscriptions</h2></div><button className={styles.secondary} disabled={!f} onClick={()=>setBill({id:'',name:'',amountCents:null,cadence:'monthly',status:'unverified',source:'',verifiedAt:null})}>Add bill</button></div><p className={styles.muted}>Record the actual plan price and billing cycle. Unknown prices are excluded from the subtotal.</p>{f?.bills.map(b=><button key={b.id} className={styles.billRow} onClick={()=>setBill(b)}><span><strong>{b.name}</strong><small>{b.status==='inactive'?'Inactive':b.status==='unverified'?'Amount / active plan unverified':`${money(b.amountCents)} / ${b.cadence==='annual'?'year':b.cadence==='weekly'?'week':'month'}`} · {b.source}</small></span><span>{b.status==='confirmed'?money(monthlyCents(b)):'—'}<ChevronRight size={15}/></span></button>)}</section>
  <footer className={styles.footer}>Private CEO view · Refreshes every 30 seconds while visible · Financial reads cached up to 15 minutes</footer>
 </div><nav className={styles.nav} aria-label='CEO navigation'><a href='#home'><House size={19}/>Home</a><a href='#team'><Bot size={19}/>Agents</a><a href='#queue'><Send size={19}/>Queue</a><a href='#bills'><Wallet size={19}/>Bills</a><button onClick={()=>setControls(true)}><Inbox size={19}/>Controls</button></nav>
 {agent&&<div className={styles.overlay}><section role='dialog' aria-modal='true' aria-labelledby='agent-title' className={styles.dialog}><div className={styles.heading}><div><h2 id='agent-title'>{agent.name}</h2><Rating health={agent.health}/></div><button className={styles.icon} aria-label='Close agent' onClick={()=>setSelected(null)}><X/></button></div><h3>What this agent does</h3><p>{agent.mandate}</p><h3>Current health</h3><p>{agent.health.reason}</p>{data.issues.filter(i=>i.department===agent.id).map(i=><div className={styles.issue} key={i.id}><strong>{i.title}</strong><p>{i.reason}</p><Link href={i.href} onClick={()=>{if(i.href.startsWith('#'))setSelected(null);}}>{i.action}</Link></div>)}<h3>Working on</h3><p>{agent.current?.message||(agent.latest?.status==='running'?'Preparing its current response.':'No active request recorded.')}</p><h3>Next assignment</h3><p>{agent.next?.message||agent.task?.title||'No new assignment waiting.'}</p><h3>Latest completed work</h3><small>{time(agent.completed?.finishedAt)}</small><p className={styles.pre}>{agent.completed?.brief||'No completed result recorded.'}</p><Link className={styles.secondary} href={agent.id==='indicator_builder'?'/owner/indicators':agent.id==='research'?'/owner/research':'/owner/team'}>Full workspace <ArrowUpRight size={16}/></Link></section></div>}
 {bill&&<div className={styles.overlay}><form className={styles.dialog} role='dialog' aria-modal='true' aria-labelledby='bill-title' onSubmit={e=>{e.preventDefault();void act('bill',{bill:{...bill,id:bill.id||bill.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,70)}});}}><div className={styles.heading}><h2 id='bill-title'>Company bill</h2><button className={styles.icon} type='button' aria-label='Close bill' onClick={()=>setBill(null)}><X/></button></div><label>Name<input required maxLength={100} value={bill.name} onChange={e=>setBill({...bill,name:e.target.value})}/></label><label>Charge in USD<input type='number' min='0' max='100000' step='0.01' value={bill.amountCents===null?'':bill.amountCents/100} onChange={e=>setBill({...bill,amountCents:e.target.value===''?null:Math.round(Number(e.target.value)*100)})}/></label><label>Billing cycle<select value={bill.cadence} onChange={e=>setBill({...bill,cadence:e.target.value as Bill['cadence']})}><option value='monthly'>Monthly</option><option value='annual'>Yearly</option><option value='weekly'>Weekly</option></select></label><label>Status<select value={bill.status} onChange={e=>setBill({...bill,status:e.target.value as Bill['status']})}><option value='unverified'>Needs verification</option><option value='confirmed'>Confirmed company expense</option><option value='inactive'>Inactive / not a company expense</option></select></label><p className={styles.muted}>This updates your records. It does not change or cancel the provider subscription.</p><button className={styles.primary} disabled={Boolean(pending)||stale}>Save bill</button></form></div>}
 </main>;
}
