import type { Department } from "../lib/business-os/policy";
export type WorkAssignment = { id: string; title: string; outcome: string; instruction: string };
const safety="Use only the data and verified product facts available to you. Separate evidence from hypotheses and say what is missing. Produce an internal deliverable; do not publish, contact anyone, spend money, change accounts, issue refunds, or claim an external action happened. Propose any such action for owner approval.";
export const workAssignments:Record<Department,WorkAssignment[]>={
  ceo:[
    {id:"today-plan",title:"Plan our best next move",outcome:"Three priorities and the next task for each relevant agent.",instruction:"Review available business evidence and open work. Rank three next steps by likely impact on acquisition, conversion, retention, or referrals. Give the relevant departments specific tasks with a success measure. Identify owner decisions and blockers. Avoid duplicate open tasks."},
    {id:"growth-review",title:"Find what’s holding us back",outcome:"A short business checkup with one recommended fix.",instruction:"Review available acquisition, conversion, retention, and referral evidence. Identify the largest supported bottleneck, distinguish missing tracking from poor performance, and recommend one small next step with the responsible department."},
    {id:"weekly-plan",title:"Make a one-week plan",outcome:"A focused weekly plan for the crew.",instruction:"Create a realistic seven-day business improvement plan using connected evidence and existing tasks. Pick one measurable outcome, assign preparation work to relevant departments, and list dependencies and approval needs. Do not invent baselines or resources."}
  ],
  growth:[
    {id:"acquisition-test",title:"Find our next customers",outcome:"One acquisition experiment with a way to measure it.",instruction:"Review verified website traffic and community click evidence. Design one low-cost customer acquisition experiment, state the audience hypothesis, draft the message, define the destination and measurement, and propose any outreach or spending for approval."},
    {id:"signup-friction",title:"Make joining easier",outcome:"A conversion improvement plan with clear checks.",instruction:"Prepare a conversion friction review using available funnel evidence. Identify unmeasured steps, propose one test to make joining or buying easier, and provide a measurement plan. Do not claim you inspected a page or checkout that is not in your evidence."},
    {id:"referral-test",title:"Plan a referral boost",outcome:"A small referral experiment for owner review.",instruction:"Design a customer referral experiment using available affiliate and growth evidence. Draft the invitation, define eligibility and measurement, and identify cost, privacy, and approval needs without offering unapproved incentives."}
  ],
  content:[
    {id:"daily-content-engine",title:"Build today’s 3 posts",outcome:"Three ready-to-review posts with audience, visual brief, CTA and destination-link purpose.",instruction:"Create three distinct Darth Algo posts for today: one educational indicator post, one product/conversion post, and one community/proof post. Follow the current Darth Algo visual system: dark premium red/black branding, chart-first layouts, large readable hooks, minimal copy, indicator-style trend candles, BUY/SELL signals, entry, stop and targets when relevant. For each post provide the target audience, hook, exact on-image copy, caption, visual brief, CTA, and funnel destination purpose. Do not invent performance or guaranteed-profit claims."},
    {id:"media-scout",title:"Tell me what fresh media to send",outcome:"A prioritized upload request that tells the owner exactly what fresh screenshots, results or clips will improve upcoming posts.",instruction:"Act as Darth Algo’s Media Scout. Review current content needs and recent team work, then ask for only the highest-value fresh assets. Request specific items such as a clean BUY setup, SELL setup, target hit, trend-candle example, community win, testimonial, desk/lifestyle photo, or short chart recording. For every requested asset explain why it is useful and give simple capture instructions. Avoid asking for assets already represented in recent work."},
    {id:"funnel-content",title:"Match posts to the right funnel",outcome:"A post-to-destination map that sends each content type to the most relevant Darth Algo next step.",instruction:"Prepare a funnel map for current content. Match educational posts, indicator demonstrations, community posts, testimonials/results, and promotional offers to the correct next step and CTA using verified Darth Algo destinations only. Flag any destination link that is unavailable or unverified instead of inventing one. Include a concise caption pattern for Instagram, Threads and X."},
    {id:"content-week",title:"Plan the next 7 days",outcome:"A seven-day content plan with 2–3 posts per day and fresh-media requests.",instruction:"Prepare a seven-day plan with 2–3 posts per day. Balance educational, indicator demonstration, community, proof/results and promotional content. Keep posts visual-first and avoid repetitive hooks. For every day include the audience, content angle, desired asset, CTA objective and success signal. Include a short Media Scout request list for anything the owner should capture fresh."}
  ],
  support:[
    {id:"onboarding-checklist",title:"Help new customers start",outcome:"A first-session checklist and help-message draft.",instruction:"Prepare an onboarding checklist that helps a new customer get their first useful experience. Use confirmed facts only and flag unknown access or setup steps. Draft a friendly help message without claiming you contacted customers or saw support tickets."},
    {id:"support-replies",title:"Write helpful reply templates",outcome:"Reusable replies for setup, access, and cancellation questions.",instruction:"Draft empathetic support reply templates for a setup problem, missing access, and a cancellation or refund question. Leave case-specific facts open. Do not invent refund policy or approve a refund; escalate sensitive cases to the owner."},
    {id:"retention-check",title:"Plan a customer check-in",outcome:"A retention check-in draft and measurement plan.",instruction:"Prepare a customer check-in plan intended to identify onboarding friction and improve retention. Draft a short message and three useful questions. Identify missing support or retention data and approvals needed before contacting customers."}
  ],
  affiliates:[
    {id:"partner-review",title:"Check our partner program",outcome:"A fact-based partner activity summary and next step.",instruction:"Review recorded affiliate applications and commission ledger. Explain what the records show, their scope, and attribution gaps. Suggest one supported next step to improve partner activation. Empty records do not prove no referrals or sales."},
    {id:"partner-kit",title:"Build a partner starter kit",outcome:"A welcome draft, checklist, and promotional copy for review.",instruction:"Prepare a partner starter kit using verified program facts: a welcome message, first-referral checklist, and two promotional copy drafts. Do not invent commission rates, payout terms, links, incentives, or performance claims."},
    {id:"partner-outreach",title:"Draft a partner invitation",outcome:"An invitation template and qualification criteria.",instruction:"Define sensible partner qualification criteria and draft a short invitation for owner review. Suggest how to measure first referral and activation. Do not invent identified leads or send messages."}
  ],
  analytics:[
    {id:"numbers-brief",title:"Explain the business numbers",outcome:"A plain-English scorecard with sources and gaps.",instruction:"Build a concise scorecard from verified sources, with source, period, scope, and limitations. Explain subscriptions, clicks, affiliate applications, commissions and content performance where available. Do not infer MRR, unique customers, conversion rates, or retention from incomplete data."},
    {id:"content-scorecard",title:"Tell us what content is winning",outcome:"A content scorecard that identifies which hooks, formats and CTAs deserve more testing.",instruction:"Compare recent content using available reach, engagement, saves, profile visits, link clicks and conversion evidence. Rank only when denominators and coverage are comparable. Identify winning patterns, weak patterns, unanswered measurement gaps, and 2–3 content changes for the next cycle."},
    {id:"tracking-plan",title:"Find our tracking gaps",outcome:"A prioritized plan to measure the customer journey.",instruction:"Map what can currently be measured across acquisition, content engagement, profile visit, link click, signup, purchase, activation, retention and referrals. Prioritize missing tracking connections and define each proposed metric and denominator."},
    {id:"check-quality",title:"Check if our numbers add up",outcome:"A data-quality check with specific follow-up checks.",instruction:"Review verified source scope, freshness, missing coverage, and inconsistent definitions. Distinguish preview database copies from live account queries. Identify data-quality issues and checks needed before making business decisions."}
  ],
  indicator_builder:[{id:"draft-review",title:"Review indicator drafts",outcome:"A specific revision or test plan for saved drafts.",instruction:"Inspect existing indicator drafts and evidence; propose concrete changes. Never claim compilation or chart validation without a real per-version test."}],
  research:[
    {id:"audience-map",title:"Map our best buyers",outcome:"A target-audience map with pains, desired outcomes, objections, hooks and content angles.",instruction:"Build a target-audience map for Darth Algo using available evidence. Separate likely buyer segments such as beginner futures traders, prop-firm/evaluation traders, scalpers, traders struggling with entries/risk, and people seeking simpler chart guidance only when supported as hypotheses. For each segment give pains, desired outcomes, objections, proof they would need, content hooks and a validation plan. Clearly separate verified facts from hypotheses."},
    {id:"community-scout",title:"Find places we can post",outcome:"A community opportunity matrix with rule status, allowed content type and safest posting approach.",instruction:"Create a community research deliverable for Reddit and X. When current public-community evidence is available, inspect current rules before recommending a destination. Classify each opportunity as direct promotion allowed, education/value only, unclear/ask moderator, or do not promote. Record rule evidence, audience fit, recommended post format, CTA restriction and risk. Never recommend rule evasion, spam, repetitive link dropping, or posting where promotion is prohibited. If live community evidence is unavailable, produce the exact source checklist needed instead of inventing communities or rules."},
    {id:"competitor-intelligence",title:"Study competitor winners",outcome:"A competitor playbook of reusable patterns without copying their creative.",instruction:"Analyze competitor evidence for audience, hooks, visual format, content frequency, offers, CTAs, social proof, community strategy, onboarding, pricing structure and recurring winning content patterns. Extract reusable tactics and translate them into original Darth Algo tests. Do not copy wording, graphics or proprietary material. Distinguish observed facts from hypotheses and include sources/timestamps when evidence is available."},
    {id:"weekly-opportunity",title:"Find this week’s best angle",outcome:"One research-backed content or acquisition opportunity for a controlled test.",instruction:"Combine target-audience, competitor, community and internal performance evidence to identify one high-value opportunity for this week. Provide the audience, problem, message angle, channel, content format, destination, success metric and stop condition. If evidence is incomplete, state exactly what needs validating first."}
  ],
  operations:[
    {id:"blocker-review",title:"Find what needs fixing",outcome:"A prioritized list of blockers and safe next steps.",instruction:"Review available source connectivity, queued or blocked work, and dependencies. Prepare a short list of problems, likely business impact, responsible department, and the next safe check. Do not claim a system was tested when it was not."},
    {id:"automation-plan",title:"Find a task to automate",outcome:"One practical automation proposal using existing systems.",instruction:"Identify one repetitive business task worth automating, prioritizing acquisition, conversion, retention, or referrals. Describe existing systems to reuse, prerequisites, approval boundaries, failure handling, and a measurable time or reliability benefit."},
    {id:"access-checklist",title:"Plan a customer access check",outcome:"A fulfillment check plan with failure and escalation steps.",instruction:"Prepare an operational checklist for purchase-to-access fulfillment, including how to verify payment, entitlement, delivery, failures, and support escalation. Use verified facts only and flag unconnected systems. Do not grant or revoke customer access."}
  ]
};
import { revenueFocus } from "../lib/business-os/business-focus";

export function assignmentMessage(assignment:WorkAssignment){return `${assignment.title}\n\n${assignment.instruction}\n\nExpected deliverable: ${assignment.outcome}\n\n${safety}\n\n${revenueFocus}`;}
