import type { Department } from "../lib/business-os/policy";
export type WorkAssignment = { id: string; title: string; outcome: string; instruction: string };
const safety="Use only the data and verified product facts available to you. Separate evidence from hypotheses and say what is missing. Produce an internal deliverable; do not publish, contact anyone, spend money, change accounts, issue refunds, or claim an external action happened. Propose any such action for owner approval.";
export const workAssignments:Record<Department,WorkAssignment[]>={
  ceo:[
    {id:"today-plan",title:"Plan our best next move",outcome:"Three priorities and the next task for each relevant agent.",instruction:"Review available business evidence and open work. Rank three next steps by likely impact on acquisition, conversion, retention, or referrals. Give the relevant departments specific tasks with a success measure. Identify owner decisions and blockers. Avoid duplicate open tasks."},
    {id:"growth-review",title:"Find what’s holding us back",outcome:"A short business checkup with one recommended fix.",instruction:"Review available acquisition, conversion, retention, and referral evidence. Identify the largest supported bottleneck, distinguish missing tracking from poor performance, and recommend one small next step with the responsible department."},
    {id:"weekly-plan",title:"Make a one-week plan",outcome:"A focused weekly plan for the crew.",instruction:"Create a realistic seven-day business improvement plan using connected evidence and existing tasks. Pick one measurable outcome, assign preparation work to relevant departments, and list dependencies and approval needs. Do not invent baselines or resources."}
  ],
  growth:[
    {id:"acquisition-test",title:"Find our next customers",outcome:"One acquisition experiment with a way to measure it.",instruction:"Review verified website traffic and community click evidence. Design one low-cost customer acquisition experiment, state the audience hypothesis, draft the message, define the destination and measurement, and propose any outreach or spending for approval."},
    {id:"signup-friction",title:"Make joining easier",outcome:"A conversion improvement plan with clear checks.",instruction:"Prepare a conversion friction review using available funnel evidence. Identify unmeasured steps, propose one test to make joining or buying easier, and provide a measurement plan. Do not claim you inspected a page or checkout that is not in your evidence."},
    {id:"referral-test",title:"Plan a referral boost",outcome:"A small referral experiment for owner review.",instruction:"Design a customer referral experiment using available affiliate and growth evidence. Draft the invitation, define eligibility and measurement, and identify cost, privacy, and approval needs without offering unapproved incentives."}
  ],
  content:[
    {id:"education-post",title:"Draft a helpful post",outcome:"One ready-to-review educational post and call to action.",instruction:"Draft one educational Darth Algo community post for a beginner, based only on verified product facts. Include a helpful takeaway and a clear next step. Flag facts needing confirmation and avoid fabricated trading results or financial promises."},
    {id:"welcome-content",title:"Create a welcome guide",outcome:"A simple first-day guide for new customers.",instruction:"Prepare a short beginner welcome guide: what Darth Algo does based on verified facts, what the customer needs first, how to get help, and an activation checklist. Mark unknown setup instructions for verification instead of inventing them."},
    {id:"content-week",title:"Plan three useful posts",outcome:"Three draft ideas that help people understand and join.",instruction:"Prepare three distinct content drafts: an educational explanation, an onboarding helper, and a buying-question answer. State the intended audience, purpose, call to action, and missing facts for each. Keep all drafts private for review."}
  ],
  support:[
    {id:"onboarding-checklist",title:"Help new customers start",outcome:"A first-session checklist and help-message draft.",instruction:"Prepare an onboarding checklist that helps a new customer get their first useful experience. Use confirmed facts only and flag unknown access or setup steps. Draft a friendly help message without claiming you contacted customers or saw support tickets."},
    {id:"support-replies",title:"Write helpful reply templates",outcome:"Reusable replies for setup, access, and cancellation questions.",instruction:"Draft empathetic support reply templates for a setup problem, missing access, and a cancellation or refund question. Leave case-specific facts open. Do not invent refund policy or approve a refund; escalate sensitive cases to the owner."},
    {id:"retention-check",title:"Plan a customer check-in",outcome:"A retention check-in draft and measurement plan.",instruction:"Prepare a customer check-in plan intended to identify onboarding friction and improve retention. Draft a short message and three useful questions. Identify missing support or retention data and approvals needed before contacting customers."}
  ],
  affiliates:[
    {id:"partner-review",title:"Check our partner program",outcome:"A fact-based partner activity summary and next step.",instruction:"Review recorded affiliate applications and commission ledger. Explain what the records show, their scope, and attribution gaps. Suggest one supported next step to improve partner activation. Empty records do not prove no referrals or sales."},
    {id:"partner-kit",title:"Build a partner starter kit",outcome:"A welcome draft, checklist, and promotional copy for review.",instruction:"Prepare a partner starter kit using verified program facts: a welcome message, first-referral checklist, and two promotional copy drafts. Do not invent commission rates, payout terms, links, incentives, or performance claims."},
    {id:"partner-outreach",title:"Draft a partner invitation",outcome:"An invitation template and qualification criteria.",instruction:"Define sensible partner qualification criteria and draft a short invitation for owner review. Suggest how to measure first referral and activation. Do not invent identified leads or send messages."}
  ],
  analytics:[
    {id:"numbers-brief",title:"Explain the business numbers",outcome:"A plain-English scorecard with sources and gaps.",instruction:"Build a concise scorecard from verified sources, with source, period, scope, and limitations. Explain subscriptions, clicks, affiliate applications, and commissions where available. Do not infer MRR, unique customers, conversion rates, or retention from incomplete data."},
    {id:"tracking-plan",title:"Find our tracking gaps",outcome:"A prioritized plan to measure the customer journey.",instruction:"Map what can currently be measured across acquisition, signup, purchase, activation, retention, and referrals. Prioritize the missing tracking connections and define each proposed metric and denominator."},
    {id:"check-quality",title:"Check if our numbers add up",outcome:"A data-quality check with specific follow-up checks.",instruction:"Review verified source scope, freshness, missing coverage, and any inconsistent definitions. Distinguish preview database copies from live account queries. Identify data-quality issues and checks needed before making business decisions."}
  ],
  research:[
    {id:"customer-questions",title:"Find what customers need",outcome:"Five research questions and a safe validation plan.",instruction:"Use available business evidence to identify five useful questions about customer needs, onboarding, or buying hesitation. State the assumptions and propose a way to validate them. Do not invent interviews, customer quotes, or survey results."},
    {id:"competitor-plan",title:"Plan a competitor review",outcome:"A comparison framework and source checklist.",instruction:"Prepare a competitor research framework covering audience, onboarding, pricing structure, proof, and support. State the sources that must be collected before comparison. Do not fabricate competitor facts or claim live web research you did not perform."},
    {id:"test-opportunity",title:"Explore one improvement",outcome:"One evidence-based hypothesis and a small test.",instruction:"Identify one plausible business improvement hypothesis using available evidence. Explain the expected customer benefit, uncertainty, test design, success measure, and stop condition without inventing market findings."}
  ],
  operations:[
    {id:"blocker-review",title:"Find what needs fixing",outcome:"A prioritized list of blockers and safe next steps.",instruction:"Review available source connectivity, queued or blocked work, and dependencies. Prepare a short list of problems, likely business impact, responsible department, and the next safe check. Do not claim a system was tested when it was not."},
    {id:"automation-plan",title:"Find a task to automate",outcome:"One practical automation proposal using existing systems.",instruction:"Identify one repetitive business task worth automating, prioritizing acquisition, conversion, retention, or referrals. Describe existing systems to reuse, prerequisites, approval boundaries, failure handling, and a measurable time or reliability benefit."},
    {id:"access-checklist",title:"Plan a customer access check",outcome:"A fulfillment check plan with failure and escalation steps.",instruction:"Prepare an operational checklist for purchase-to-access fulfillment, including how to verify payment, entitlement, delivery, failures, and support escalation. Use verified facts only and flag unconnected systems. Do not grant or revoke customer access."}
  ]
};
import { revenueFocus } from "../lib/business-os/business-focus";

export function assignmentMessage(assignment:WorkAssignment){return `${assignment.title}\n\n${assignment.instruction}\n\nExpected deliverable: ${assignment.outcome}\n\n${safety}\n\n${revenueFocus}`;}
