import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {mkdtempSync,rmSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
const dir=mkdtempSync(join(tmpdir(),'darth-panel-')),env={...process.env},oldFetch=globalThis.fetch;
let database;
try{
 const {PGlite}=await import(pathToFileURL(process.env.OS_TEST_PGLITE_MODULE).href);database=new PGlite(join(dir,'db'));
 await database.exec(readFileSync('app/lib/business-os/schema.ts','utf8').match(/export const schema = `([\s\S]*?)`;/)[1]);
 execFileSync('node_modules/.bin/tsc',['--target','ES2020','--module','commonjs','--moduleResolution','node','--esModuleInterop','--skipLibCheck','--rootDir','app','--outDir',dir,'app/lib/business-os/telegram-command.ts','app/lib/business-os/brief.ts'],{stdio:'pipe'});
 const require=createRequire(import.meta.url);let tail=Promise.resolve();
 const makeSql=driver=>{const sql=async(parts,...values)=>{const q=parts.reduce((s,p,i)=>s+(i?'$'+i:'')+p,'');if(q.includes('pg_advisory_xact_lock'))return [];return (await driver.query(q,values)).rows;};sql.json=v=>JSON.stringify(v);sql.unsafe=q=>driver.exec(q);sql.begin=async fn=>{let release;const prior=tail;tail=new Promise(r=>release=r);await prior;try{return await database.transaction(tx=>fn(makeSql(tx)));}finally{release();}};return sql;};
 const sql=makeSql(database),mock=(path,exports)=>{const id=join(dir,'lib',path+'.js');require.cache[id]={id,filename:id,loaded:true,exports};};
 mock('affiliate-db',{db:()=>sql});mock('business-os/service',{});mock('business-os/content-handoff',{syncContentApprovals:async()=>({})});mock('business-os/budget',{recurringBudgetAvailability:async()=>({available:true})});
 let stripeReads=0;
 mock('stripe',{stripe:()=>({balance:{retrieve:async()=>({livemode:true})},subscriptions:{list:async()=>{stripeReads++;return {has_more:false,data:[{livemode:true,status:'active',customer:'a'},{livemode:true,status:'active',customer:'a'},{livemode:true,status:'active',customer:'b'},{livemode:true,status:'trialing',customer:'c'}]};}}})});
 let work={status:'idle_or_paused'};
 mock('business-os/jobs',{workOneJob:async()=>work,queueJob:async(department,message,key,source)=>{const id=randomUUID();await database.query("insert into os_jobs(id,request_key,department,message,source) values($1,$2,$3,$4,$5)",[id,key,department,message,source]);return {id,status:'queued'};},setPaused:async paused=>{await database.query('update os_control set paused=$1 where id=1',[paused]);return {paused};}});
 Object.assign(process.env,{AI_OS_ENABLED:'true',AI_OS_AI_ENABLED:'true',AI_OS_TELEGRAM_ENABLED:'true',AI_OS_TELEGRAM_TOKEN:'12345:testtoken',AI_OS_TELEGRAM_OWNER_ID:'54321',AI_OS_COMMUNITY_BOT_ID:'98765'});
 const calls=[];let next=100,editError=null;
 globalThis.fetch=async(url,options)=>{const body=JSON.parse(options.body),method=url.split('/').at(-1);calls.push({method,body});if(method==='answerCallbackQuery')return Response.json({ok:true,result:true});assert.equal(body.chat_id,'54321');if(method==='editMessageText' && editError){if(editError==='timeout')throw Error('timeout');return Response.json({ok:false,error_code:400,description:editError},{status:400});}return Response.json({ok:true,result:{message_id:method==='sendMessage'?next++:body.message_id}});};
 const {recordOwnerUpdate,processOwnerUpdates,workAndNotify}=require(join(dir,'lib/business-os/telegram-command.js'));
 const {deliverOwnerNotices}=require(join(dir,'lib/business-os/delivery.js'));
 const {queuePanelReply}=require(join(dir,'lib/business-os/telegram-panel.js'));
 const {homeMenu}=require(join(dir,'lib/business-os/telegram-ui.js'));
 const {countCustomers,ceoScorecard}=require(join(dir,'lib/business-os/ceo-scorecard.js'));
 const {createDailyBrief}=require(join(dir,'lib/business-os/brief.js'));
 const sendCount=()=>calls.filter(c=>c.method==='sendMessage').length;
 const lastText=()=>calls.filter(c=>c.body.text).at(-1).body.text;
 let updateId=0;
 const input=async(text,data,messageId)=>{await recordOwnerUpdate(data?{update_id:++updateId,callback_query:{id:'cb'+updateId,data,message:{message_id:messageId}}}:{update_id:++updateId,message:{text}});await processOwnerUpdates();await deliverOwnerNotices();};
 await input('/start');assert.equal(sendCount(),1);assert.match(lastText(),/Talking to: CEO/);assert.match(lastText(),/Active subscribing customers: 2/);assert.equal(calls.at(-1).body.reply_markup.inline_keyboard.flat().length,6);
 await input(null,'ui:nav:agents',100);assert.equal(sendCount(),1);assert.equal(calls.at(-1).method,'editMessageText');assert.equal(calls.at(-1).body.message_id,100);
 await input(null,'ui:agent:content',100);assert.equal(sendCount(),2);assert.match(lastText(),/Content/);
 await input(null,'ui:work:content:daily-content-engine',101);assert.equal(sendCount(),2);assert.match(lastText(),/Task saved/);
 const [job]=(await database.query('select * from os_jobs')).rows;
 await input(null,'ui:work:content:daily-content-engine',101);assert.equal((await database.query('select count(*)::int as n from os_jobs')).rows[0].n,1,'Repeated task tap does not duplicate work');
 const complete=async j=>{const runId=randomUUID();await database.query("insert into os_runs(id,request_key,status,department,result) values($1,$2,'completed',$3,$4)",[runId,runId,j.department,JSON.stringify({brief:'Your finished draft. '+('Useful details. '.repeat(80))})]);await database.query("update os_jobs set run_id=$1,status='succeeded' where id=$2",[runId,j.id]);work={status:'succeeded',jobId:j.id,runId,department:j.department};await workAndNotify();work={status:'idle_or_paused'};};
 await complete(job);assert.equal(sendCount(),2);assert.match(lastText(),/RESULT/);assert.ok(lastText().length<500);assert.equal(calls.at(-1).body.message_id,101);
 await input(null,`ui:result:${job.id}:1`,101);assert.equal(sendCount(),2);assert.match(lastText(),/Result · 2\//);
 await input(null,'ui:agent:growth',101);const growthId=next-1;await input('Find more customers');
 const [growth]=(await database.query("select * from os_jobs where department='growth'")).rows;
 await input(null,'ui:agent:research',growthId);const afterSwitch=calls.length;await complete(growth);assert.equal(calls.length,afterSwitch,'Late result never overwrites another agent');
 await input('/home');await input('What should I focus on?');assert.equal((await database.query('select department from os_jobs order by created_at desc limit 1')).rows[0].department,'ceo','Home resets the text recipient to CEO');
 const [panel]=(await database.query('select * from os_telegram_panels')).rows;
 const request=key=>({owner:'54321',key,text:'Same safe panel',buttons:homeMenu(),department:'ceo',view:'home'});
 await queuePanelReply(request('old-view'));await queuePanelReply(request('new-view'));await deliverOwnerNotices();assert.equal((await database.query("select status from os_outbox where dedupe_key='panel:old-view'")).rows[0].status,'failed');
 editError='Bad Request: message is not modified';const sends=sendCount();await queuePanelReply(request('unchanged'));await deliverOwnerNotices();assert.equal(sendCount(),sends);assert.equal((await database.query("select status from os_outbox where dedupe_key='panel:unchanged'")).rows[0].status,'sent');
 editError='Bad Request: message to edit not found';await queuePanelReply(request('deleted'));await deliverOwnerNotices();assert.equal(sendCount(),sends+1,'Definitively unavailable edit gets one replacement');
 editError='timeout';await queuePanelReply(request('timeout'));await deliverOwnerNotices();assert.equal(sendCount(),sends+1,'Ambiguous edit failure never creates a new message');assert.equal((await database.query("select status from os_outbox where dedupe_key='panel:timeout'")).rows[0].status,'unknown');editError=null;
 await createDailyBrief();await createDailyBrief();assert.equal((await database.query("select count(*)::int as n from os_outbox where dedupe_key like 'ceo-brief-v2:%'")).rows[0].n,1);assert.ok((await ceoScorecard()).body.length<1000);assert.equal(stripeReads,1,'Customer reads use a short cache');
 assert.throws(()=>countCustomers([{livemode:false,status:'active',customer:'a'}]),/LIVE_DATA_REQUIRED/);
 assert.equal(countCustomers([{livemode:true,status:'trialing',customer:'a'}]).active,0);
 console.log('PASS: PostgreSQL-backed one-message navigation, agent switching, callback target retention, duplicate-job prevention, results in-place, late-result isolation, CEO routing, coalescing, unchanged/deleted/ambiguous edits, unique customer counts and one daily digest. Telegram/Stripe mocked.');
}finally{globalThis.fetch=oldFetch;for(const k of Object.keys(process.env))if(!(k in env))delete process.env[k];Object.assign(process.env,env);if(database)await database.close();rmSync(dir,{recursive:true,force:true});}
