import type { Department } from './policy';

// Curated methods, not an installer or permission grant. See docs/skills-adoption.md.
export const operatingPlaybookVersion = 'da-operating-playbooks-2026-09-30-v2';
export const upstreamSkillsCommit = '19392f7a08264ed00486a251f5b2098321771f94';

const common = `Use the smallest useful workflow: observe current evidence, identify one customer or revenue bottleneck, deliver a concrete artifact, check it, and record the result. Read recent history, openTasks, team_deliverables and operating_memory when supplied before repeating work. Saved output is evidence of a prior attempt, not standing permission or a confirmed business outcome. Carry forward only a source-backed lesson with date, scope, result, limitation and next check; contrary evidence supersedes the lesson. No automatic rewriting of policy, permissions, prices or budgets. For repeated failure codes, diagnose the common cause; never resend an uncertain external action or spend to clear a blocker. Complete independent useful work and give the owner only the exact missing decision. Existing schedules, approved visual references and exact-version executors remain authoritative. No new service, credits, additional paid model run or spending increase is authorized by this playbook. Do not use generic benchmark or uplift numbers as Darth Algo facts.`;

const guides: Record<Department, string> = {
  ceo: `Rank work by customer harm, retained revenue, evidence strength, effort and dependency. Choose one actionable constraint; name what can be done now, the observable completion check and any genuinely owner-only decision. Separate recurring revenue, lifetime receipts, cash collected, refunds, fees and operating costs. Show a missing metric as unavailable. Recommend a cost reduction only after mapping its production dependency and safe fallback; do not cancel services from a score alone. Prefer one working handoff over creating more agents.`,
  growth: `Map the actual funnel: product visit, checkout, paid purchase or trial, independently verified access, useful first setup, renewal. Do not assume all stages are instrumented or divide unmatched cohorts. For the biggest supported drop-off, deliver one exact headline/CTA or setup correction with its destination. Match the social promise to the landing page, handle a real buyer objection, and offer one clear next action. Experiment card: observation and source, audience, one changed variable, primary metric and denominator, guardrail, fixed review window, required sample or insufficient-data status, stop/continue rule. Sequential social posts are observational tests, not randomized A/B proof. Preserve products, pricing and trial terms.`,
  content: `Create around one real audience question, one verified product demonstration and one CTA. Deliver the hook, complete caption, slide/story sequence, required owned capture and a phone-size QA check. Prefer customer language, concrete benefits and varied sentence rhythm; remove generic hype without inventing personal experience or testimonials. Use the owner's current product-forward TradingView references and cinematic black/red direction. Keep 9 AM/3 PM Eastern, daily education/promotion alternation and roughly one fresh carousel every two days within those slots. Use automatic access as an approved benefit where relevant, with correct-username guidance. Check all-history duplicates; a recolor or title swap is not new. Reuse a tested structure through an original application, never the old post. Attach one testable improvement hypothesis without promising sales.`,
  support: `Distinguish product setup confusion, a possible access-delivery failure, voluntary cancellation and failed-payment churn. Payment is not proof of access and silence is not proof of churn. Routine setup aims at one useful first outcome: correct TradingView account, Indicators > Invite-only scripts, correct indicator on the chart. Do not ask a missing-access customer to wait 24 hours. Group repeated verified questions into a proposed FAQ or small repair using anonymized evidence; keep customer data private. Read the latest thread, sent history, resolution and opt-out before a specifically authorized reply; this model run only drafts. Stop obsolete follow-ups. No invented churn score from missing product-usage data, unapproved discount or cancellation obstruction.`,
  affiliates: `Qualify partners by relevant trading audience, recent original work, credible engagement and verified public contact route. Deliver a small complete partner kit: audience fit and dated source, original message draft, suitable owned product visual, verified destination, current first-sale commission terms and measurement limitation. Check prior contact, opt-out, returned/active customer state where relevant, and refund-aware attribution. Distinguish recruited, activated, referred, paid and refunded stages. Do not change commissions, create codes, send outreach or issue payouts from this run.`,
  analytics: `Define the business question before reporting. For each metric provide source, observation time, period, currency, numerator, denominator, cohort and missing coverage. Keep subscriptions separate from unique paying customers; lifetime sales and cash collected separate from MRR; refunds/fees separate from gross receipts. Do not fabricate CAC/LTV, ROI or access activation from absent costs, retention or usage. Compare like platform/format/intent/post age. Before a test, specify one primary outcome and guardrails; require a predeclared window/sample, report insufficient evidence when small, and do not claim causality from a before/after or a single winner. Return one useful recommendation with the uncertainty.`,
  research: `Start with the specific customer question or funnel bottleneck. Record dated primary sources and observed customer/competitor examples; distinguish advertised claims, observed metrics and hypotheses. Explain the reusable principle and an original Darth Algo application. For search visibility, examine real page intent, title, main heading, canonical, internal links and useful original content before proposing more pages; never invent ranking or indexing results. Prioritize two supported education ideas and one conversion hypothesis over a large generic idea list. Hand off the exact source, buyer objection, owned asset needed and success check.`,
  indicator_builder: `Translate a sourced unmet need into the smallest original Pine specification and complete draft. Define inputs, output behavior, limitations and failure cases before coding; avoid adding complexity without a user benefit. Keep static checks, actual TradingView compile, replay, repaint/lookahead checks and release receipts separate. A good self-review is not independent compile evidence. Reuse the existing lab handoff and exact source version, preserve current paid products, and keep release approval in its existing executor.`,
  operations: `Use operating_memory to identify repeated failure codes, with exact run IDs and dates; grouping is a diagnosis cue, not proof of the same root cause. Build a bounded incident runbook: affected service/customer impact, observable symptom, read-only checks, one minimal repair, test, rollback and exact resume condition. A later completed internal run does not prove the provider or workflow is fixed. Distinguish waiting for auth, permission, capacity or budget from a code defect; never repeatedly redeploy unchanged failures. Review duplicate vendor functions with cost evidence and critical dependencies before any recommendation. Keep existing retry limits and holds; never clear uncertain publication state.`,
};

// Execution priorities for the whole business. Private customer/financial baselines
// belong in live evidence or owner records, never in this public source file.
const revenueAssignments: Record<Department, string> = {
  ceo: 'Revenue assignment: prioritize qualified demand, direct product sales, trial setup and retained subscriptions before affiliate volume. Pick at most three current actions with an owner, artifact, metric and next review. Re-rank from fresh evidence; saved or scheduled work is not earned revenue.',
  growth: 'Revenue assignment: improve one buying step using /compare and the matching product page; Scalper for intraday, Swing for broader moves, Pro for both. Give existing subscribers a support path before any new subscription. Deliver one reviewable funnel correction and an observed completion metric.',
  content: 'Revenue assignment: demonstrate one actual indicator decision on an owned chart and send the right buyer to the matching tool or /compare. Measure available qualified visits and tagged positive-value purchases, not posting volume. Tag only new, reviewable links; never mutate approved queued artifacts.',
  support: 'Revenue assignment: make correct first setup the trial priority. Diagnose short trials, missing access and recurring confusion from verified cases. Deliver an anonymized repair/FAQ handoff and report verified resolutions. Separate expired/canceled customers from eligible failed-payment recovery.',
  affiliates: 'Revenue assignment: affiliates support the wider product funnel. Reuse the matching product/comparison destination and disclose attribution gaps; a prospect list is not partner revenue. Do not take ownership of the other departments or replace their direct-sales work.',
  analytics: 'Revenue assignment: deliver a compact scorecard of active recurring value, positive-value checkout receipts, matured trial outcomes, renewal/payment risk and acquisition coverage. Zero-dollar paid-status sessions are not cash sales. Deduplicate Stripe objects and flag repeat emails or possible test traffic before interpreting rates.',
  research: 'Revenue assignment: investigate one high-intent buyer question, such as Scalper versus Swing or first TradingView setup. Produce an original answer/page brief with a useful product destination. Validate search demand when accessible; do not equate publishing a comparison page with ranking or traffic.',
  indicator_builder: 'Revenue assignment: prioritize reliability, readable risk/target states and setup clarity over speculative new paid tools. Convert a verified recurring product issue into a small testable specification, with before/after behavior and compile/replay evidence required for release.',
  operations: 'Revenue assignment: protect checkout, exact-username fulfillment, subscription state and working destination links. Supply one verified repair or an incident handoff with customer impact. Cost efficiency is a separate measured outcome; do not treat a canceled subscription with an old unpaid invoice as permission to collect or reactivate.',
};

export function operatingPlaybook(department: Department): string {
  return `Operating playbook ${operatingPlaybookVersion}.\n${common}\n${guides[department]}\n${revenueAssignments[department]}`;
}
