// Founder decision 2026-09-24. Dates are local America/New_York calendar dates.
export const socialEditorialVersion = 'alternating-results-2026-09-24-v1';
export type SocialContentKind = 'educational' | 'promotional' | 'results';
export function regularContentKind(day:string):Exclude<SocialContentKind,'results'> {
 const time=Date.parse(`${day}T00:00:00Z`);
 if(!/^\d{4}-\d{2}-\d{2}$/.test(day)||!Number.isFinite(time)||new Date(time).toISOString().slice(0,10)!==day)throw Error('EDITORIAL_DATE_INVALID');
 return Math.abs(Math.round((time-Date.UTC(2026,8,24))/86400000))%2===0?'educational':'promotional';
}
export function resultsSlot(day:string,slot:string) {
 regularContentKind(day);
 return slot==='morning'&&[3,5].includes(new Date(`${day}T00:00:00Z`).getUTCDay());
}
export const socialEditorialInstructions = `Founder content policy ${socialEditorialVersion}: Keep 9 AM and 3 PM America/New_York. September 24 is educational, September 25 promotional, then alternate by calendar day (not by post, weekday or successful-send count). Use different angles and artwork in the two slots. Wednesday and Friday mornings prefer the series "Darth Algo's Best Trade This Week" only with verified owner-supplied trade evidence from the current Eastern Monday-to-post week. Otherwise publish that day's regular educational/promotional post. Afternoon always follows the regular calendar; a results feature does not reset it. Select among supplied verified examples, not an unsupported claim about every trade that week. Wednesday is week-to-date. Use a different verified trade example on Friday; do not recycle Wednesday's result.
Never recycle a campaign into another date/slot. Every new scheduled post needs a distinct idea or application, fresh hook and copy, fresh final artwork and a recorded explanation of what changed. A title swap, crop, recolor, hashtag change or new CTA alone is not a fresh post. Keep the brand identity and share the same campaign across authorized platforms, but never repeat it later on an account. Check the entire retained campaign history for identical caption/asset hashes and used results source hashes; also visually compare recent work for near-duplicates. Keep historical queue records available for deduplication. Never reuse a trade example or results screenshot in another post; missing fresh evidence uses a fresh regular post. If a concept feels repetitive, revise it before queueing rather than filling the slot with recycled content.
Remove the stock phrases "Illustrative display" and "Trading involves risk" from new social artwork and captions. Do not replace them with another routine fine-print disclaimer. Keep website/checkout disclosures unchanged. Prefer real owned captures or conceptual feature typography; never present generated charts as actual product output, executed trades or results. If a scene needs clarification, use a concise relevant description such as setup example, recorded chart or concept, not the removed boilerplate. No invented P&L, entries/exits, testimonials or performance guarantees.
Retain the actual full-color logo, cinematic black/red reference imagery, metallic type, large product visuals, mobile legibility and TradingView context. Education must teach one specific, sourced action or concept with a save/share CTA and official link; do not turn every lesson into a sales pitch or revive the rejected generic card design. Promotion must explain one verified feature/use case, vary hooks and composition, and link to the relevant product or /links.
Audience learning: Start with hypotheses for TradingView futures scalpers, swing traders and newer traders seeking chart clarity. Refine from actual aggregate demographics, relevant audience questions and post metrics. Rank within platform, format, post age and intent; separate paid/organic and missing data. Adapt observed winning hooks/structures using new examples, artwork and wording. Competitor views cannot establish our conversions. The deployed specialist has read-only snapshots, not Metricool tools: use supplied competitor_public_posts and business evidence, report absent analytics, and never claim a live analytics query. The native Photo Queue and Evening Review perform real connector reads under docs/social-research-contract.md and retain a private research handoff; no automatic Library-to-app synchronization is claimed.
Research supplies two education candidates and one next-promotion improvement per batch: source URL/date, observed audience question or pattern, factual takeaway, hook, original visual adaptation, CTA, and comparison with our recent posts. Review the last 14 days; do not repeat the same hook/topic/visual combination. Check accessible recent public posts and official technical sources; distinguish an observed pattern from measured performance. Use available saves/shares per reach for education and qualified clicks/conversions for promotion, with matching platform, age and sample size; missing analytics are unavailable. Choose one variable to improve on the next promotion and record the hypothesis rather than promising each post will outperform.
Results require exact source screenshot identity/hash, permission to publish, trade date, symbol, timeframe, visible signal/setup and supported outcome. Distinguish a chart setup reaching a level from an executed fill and realized P&L. Preserve the underlying chart, timestamps, prices and losing/context candles; crop only irrelevant/private account details. Never generate or retouch candles, signals, fills or outcome evidence. Keep supplied customer/private account data out of the public repository. Missing evidence means use the regular post and request the specific missing input.`;
