// Founder decision 2026-09-24. Dates are local America/New_York calendar dates.
export const socialEditorialVersion = 'alternating-results-2026-09-24-v1';
export type SocialContentKind = 'educational' | 'promotional' | 'results';
export function regularContentKind(day:string):Exclude<SocialContentKind,'results'> {
 const time=Date.parse(`${day}T00:00:00Z`);
 if(!/^\d{4}-\d{2}-\d{2}$/.test(day)||!Number.isFinite(time)||new Date(time).toISOString().slice(0,10)!==day)throw Error('EDITORIAL_DATE_INVALID');
 return Math.abs(Math.round((time-Date.UTC(2026,8,24))/86400000))%2===0?'educational':'promotional';
}
export function resultsSlot(day:string,slot:string) {
 regularContentKind(day);
 return slot==='morning'&&[3,5].includes(new Date(`${day}T00:00:00Z`).getUTCDay());
}
export const socialEditorialInstructions = `Founder content policy ${socialEditorialVersion}: Keep 9 AM and 3 PM America/New_York. September 24 is educational, September 25 promotional, then alternate by calendar day (not by post, weekday or successful-send count). Use different angles and artwork in the two slots. Wednesday and Friday mornings prefer the series "Darth Algo's Best Trade This Week" only with verified owner-supplied trade evidence from the current Eastern Monday-to-post week. Otherwise publish that day's regular educational/promotional post. Afternoon always follows the regular calendar; a results feature does not reset it. Select among supplied verified examples, not an unsupported claim about every trade that week. Wednesday is week-to-date. Do not reuse Wednesday's example Friday unless clearly identified as a recap with a useful new explanation.
Remove the stock phrases "Illustrative display" and "Trading involves risk" from new social artwork and captions. Do not replace them with another routine fine-print disclaimer. Keep website/checkout disclosures unchanged. Prefer real owned captures or conceptual feature typography; never present generated charts as actual product output, executed trades or results. If a scene needs clarification, use a concise relevant description such as setup example, recorded chart or concept, not the removed boilerplate. No invented P&L, entries/exits, testimonials or performance guarantees.
Retain the actual full-color logo, cinematic black/red reference imagery, metallic type, large product visuals, mobile legibility and TradingView context. Education must teach one specific, sourced action or concept with a save/share CTA and official link; do not turn every lesson into a sales pitch or revive the rejected generic card design. Promotion must explain one verified feature/use case, vary hooks and composition, and link to the relevant product or /links.
Research supplies two education candidates and one next-promotion improvement per batch: source URL/date, observed audience question or pattern, factual takeaway, hook, original visual adaptation, CTA, and comparison with our recent posts. Review the last 14 days; do not repeat the same hook/topic/visual combination. Check accessible recent public posts and official technical sources; distinguish an observed pattern from measured performance. Use available saves/shares per reach for education and qualified clicks/conversions for promotion, with matching platform, age and sample size; missing analytics are unavailable. Choose one variable to improve on the next promotion and record the hypothesis rather than promising each post will outperform.
Results require exact source screenshot identity/hash, permission to publish, trade date, symbol, timeframe, visible signal/setup and supported outcome. Distinguish a chart setup reaching a level from an executed fill and realized P&L. Preserve the underlying chart, timestamps, prices and losing/context candles; crop only irrelevant/private account details. Never generate or retouch candles, signals, fills or outcome evidence. Keep supplied customer/private account data out of the public repository. Missing evidence means use the regular post and request the specific missing input.`;
