import {ownerSessionFromRequest,privateHeaders,sameOrigin} from "../../../../lib/business-os/owner-session";
import {browserStatus,browserView,connectBrowser,startBrowser,stopBrowser} from "../../../../lib/business-os/hosted-browser";
export const runtime="nodejs";
export const dynamic="force-dynamic";
export const maxDuration=60;
const headers={...privateHeaders,"Referrer-Policy":"no-referrer"};
function allowed(r:Request){return ownerSessionFromRequest(r)&&sameOrigin(r)&&process.env.VERCEL_ENV==="production"&&r.headers.get("host")==="www.darthalgo.com";}
export async function GET(r:Request){if(!ownerSessionFromRequest(r))return Response.json({error:"Unauthorized"},{status:401,headers});try{return Response.json(new URL(r.url).searchParams.has("view")?await browserView():await browserStatus(),{headers});}catch{return Response.json({error:"Browser status unavailable. The viewer has been hidden; refresh before retrying."},{status:503,headers});}}
export async function PUT(r:Request){if(!allowed(r))return Response.json({error:"Open the live owner workspace"},{status:403,headers});if(!r.headers.get("content-type")?.startsWith("application/json"))return Response.json({error:"JSON required"},{status:415,headers});const raw=await r.text();if(raw.length>5000)return Response.json({error:"Key too long"},{status:413,headers});try{const b=JSON.parse(raw);if(typeof b.key!=="string")throw Error();await connectBrowser(b.key.trim());return Response.json({connected:true},{headers});}catch{return Response.json({error:"Connection could not be verified. Check the key and wait for any existing session to finish."},{status:400,headers});}}
export async function POST(r:Request){if(!allowed(r))return Response.json({error:"Unauthorized"},{status:403,headers});try{if(new URL(r.url).searchParams.get("action")==="test"){const {queueHostedCheck}=await import("../../../../lib/business-os/hosted-checks");return Response.json(await queueHostedCheck(),{headers});}return Response.json(await startBrowser(),{headers});}catch(e){return Response.json({error:e instanceof Error?e.message:"Session could not start"},{status:409,headers});}}
export async function DELETE(r:Request){if(!allowed(r))return Response.json({error:"Unauthorized"},{status:403,headers});try{await stopBrowser();return Response.json({active:false},{headers});}catch{return Response.json({error:"Stop is unconfirmed. The session still has a 15-minute timeout."},{status:503,headers});}}
