"use client";
import {useCallback,useEffect,useRef,useState,type FormEvent} from "react";
import Link from "next/link";
type Status={connected:boolean;remainingPilotStarts:number;expiresAt:string|null;tradingViewVerified:boolean;verificationStatus:string|null;latestCheck:null|{status:string;error_code:string|null}};
type View={active:boolean;url?:string;expiresAt?:string};
export default function BrowserConnection(){
 const [status,setStatus]=useState<Status|null>(null),[view,setView]=useState<View>({active:false}),[key,setKey]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now());
 const frame=useRef<HTMLIFrameElement>(null);
 const request=useCallback(async(method="GET",body?:unknown,query="")=>{const r=await fetch(`/api/owner/connections/browser${query}`,{method,cache:"no-store",headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error||"Connection unavailable");return data;},[]);
 const refresh=useCallback(async()=>{try{setStatus(await request());}catch{setMessage("Open your private owner workspace in this browser first, then refresh this page.");}},[request]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[refresh]);
 useEffect(()=>{if(!view.active)return;const check=async()=>{try{const next=await request("GET",undefined,"?view=1");if(!next.active){setView({active:false});setMessage("This session has ended. The old screen has been removed.");}}catch{setView({active:false});setMessage("Connection lost. Use Reconnect viewer to check the existing session.");}};const timer=setInterval(()=>void check(),15000);return()=>clearInterval(timer);},[view.active,request]);
 useEffect(()=>{const disconnected=(e:MessageEvent)=>{if(!view.url||e.source!==frame.current?.contentWindow||e.origin!==new URL(view.url).origin||e.data!=="browserbase-disconnected")return;setView({active:false});setMessage("The hosted browser disconnected. Reconnect the viewer to check whether the session is still running.");};window.addEventListener("message",disconnected);return()=>window.removeEventListener("message",disconnected);},[view.url]);
 const seconds=view.expiresAt?Math.max(0,Math.floor((new Date(view.expiresAt).getTime()-60000-now)/1000)):0;
 useEffect(()=>{if(view.active&&seconds===0){setView({active:false});setMessage("The 15-minute session has ended. The old screen has been removed.");}},[seconds,view.active]);
 const checkStatus=status?.latestCheck?.status;
 useEffect(()=>{if(!checkStatus||!['queued','running'].includes(checkStatus))return;const timer=setInterval(()=>void refresh(),10000);return()=>clearInterval(timer);},[checkStatus,refresh]);
 async function act(method:string,body?:unknown,query=""){setBusy(true);setMessage("");try{const result=await request(method,body,query);if(method==="PUT"){setKey("");setMessage("Browserbase connected. TradingView sign-in has not been verified yet.");}else if(query==="?action=test"){setView({active:false});setMessage("Test queued. You can close this page; the server will check the saved source and chart. Keep other TradingView sessions closed during the test.");}else{setView(result);if(!result.active)setMessage(method==="DELETE"?"Session stopped. Allow the saved profile to finish syncing before starting another.":"No active session. Start a new sign-in session when available.");}await refresh();}catch(e){setMessage(e instanceof Error?e.message:"Please refresh status.");}finally{setBusy(false);}}
 const button="rounded-xl bg-violet-600 px-5 py-3 font-semibold text-white disabled:opacity-40";
 return <main className="mx-auto min-h-screen max-w-[1600px] px-5 py-8 text-white"><Link href="/owner/connections" className="text-violet-300">← Agent connections</Link><h1 className="mt-6 text-3xl font-semibold">TradingView browser setup</h1><p className="mt-3 text-slate-300">A private browser for your indicator agent. Sign in only inside the live window below. Finish sign-in, then run the saved-chart test. Public indicator releases still require a tested package and your approval.</p>{message&&<p role="status" className="my-5 rounded-xl border border-violet-400/40 p-4">{message}</p>}
 {!status?.connected?<form className="my-8 max-w-xl rounded-2xl border border-white/20 p-6" onSubmit={(e:FormEvent)=>{e.preventDefault();void act("PUT",{key});}}><h2 className="text-xl font-semibold">Connect your existing Browserbase account</h2><p className="my-3 text-slate-300">Copy the API key from your Browserbase dashboard. This verifies your existing Darth Algo profile without starting a paid session.</p><label htmlFor="browser-key">Browserbase API key</label><input id="browser-key" type="password" autoComplete="off" spellCheck={false} maxLength={4096} value={key} onChange={e=>setKey(e.target.value)} className="my-3 block w-full rounded-lg border border-white/20 bg-black/30 p-3"/><p className="mb-4 text-sm text-slate-400">Encrypted on the server. Your key is never shown again.</p><button className={button} disabled={busy||!status||!key.trim()}>Save connection</button></form>:<div className="my-6 flex flex-wrap gap-3"><button className={button} disabled={busy||view.active||status.remainingPilotStarts===0||!!(status.expiresAt&&new Date(status.expiresAt).getTime()>now)} onClick={()=>void act("POST")}>Start sign-in session</button><button className={button} disabled={busy} onClick={()=>void act("GET",undefined,"?view=1")}>Reconnect viewer</button><button className={button} disabled={busy||!view.active||status.latestCheck?.status==='running'||status.latestCheck?.status==='queued'} onClick={()=>void act("POST",undefined,"?action=test")}>Finish sign-in &amp; test</button><button className={button} disabled={busy||status.latestCheck?.status==='running'} onClick={()=>void act("DELETE")}>Stop session</button><button className={button} disabled={busy} onClick={()=>void refresh()}>Refresh status</button><p className="self-center text-sm text-slate-400">{status.remainingPilotStarts} approved starts left · 15 minutes each · No upgrades</p></div>}
 {view.active&&view.url?<section><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><p>Live browser · {Math.floor(seconds/60)}:{String(seconds%60).padStart(2,"0")} remaining</p><a href={view.url} target="_blank" rel="noreferrer" className="text-violet-300 underline">Open full-size window ↗</a></div><p className="mb-3 text-sm text-slate-300">In the browser address bar, open https://www.tradingview.com/ and sign in. After signing in, tap Finish sign-in & test. The server checks the private chart and saves the profile when it closes the session.</p><iframe ref={frame} src={view.url} title="Private hosted TradingView browser" referrerPolicy="no-referrer" allow="clipboard-read; clipboard-write" sandbox="allow-same-origin allow-scripts" className="h-[78vh] min-h-[600px] w-full rounded-xl border border-white/20 bg-white"/></section>:<section className="rounded-2xl border border-white/15 p-8 text-slate-300">No sign-in window is open. Start a session to sign in, or check your latest test result below.</section>}
 <section className="mt-6 rounded-2xl border border-white/15 p-6"><h2 className="text-xl font-semibold">Private chart test</h2><p className="mt-3">{status?.latestCheck?.status==='checked'?'Saved source and chart verified.':status?.latestCheck?.status==='queued'?'Queued · starts within five minutes.':status?.latestCheck?.status==='running'?'Checking the saved indicator…':status?.latestCheck?.status==='blocked'?`Needs attention: ${status.latestCheck.error_code?.replaceAll('_',' ').toLowerCase()}`:'Waiting for sign-in and test.'}</p><p className="mt-3 text-sm text-slate-400">Checks the existing Opening Range Fakeout private beta on four intervals and reopens its saved chart. This does not publish an indicator or certify its signals, replay, or trading results.</p>{status?.remainingPilotStarts===0&&<p className="mt-3 text-sm text-amber-300">Your approved browser session allowance is used. An active session can still be tested. More browser time requires a reviewed allowance before another session can start.</p>}</section>
 </main>;
}
