"use client";
import { FormEvent, useEffect, useState } from "react";

type Application={id:string;created_at:string;status:string;full_name:string;email:string;tradingview_username:string;primary_platform:string;profile_url:string;audience_size:string;content_plan:string;preferred_code:string;payout_method:string;payout_handle:string;commission_rate_bps:number};

export default function AdminAffiliates(){const[key,setKey]=useState('');const[items,setItems]=useState<Application[]>([]);const[error,setError]=useState('');const[busy,setBusy]=useState('');
  async function load(value=key){const r=await fetch('/api/admin/affiliates',{headers:{'x-admin-key':value}});if(!r.ok){setError('Admin key is incorrect.');return;}sessionStorage.setItem('affiliate-admin-key',value);setItems((await r.json()).applications);setError('');}
  // Restore the key only for this browser tab; it is never persisted to the server or local storage.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{const saved=sessionStorage.getItem('affiliate-admin-key');if(saved){setKey(saved);void load(saved)}},[]);
  async function act(id:string,action:string){setBusy(id+action);const r=await fetch(`/api/admin/affiliates/${id}`,{method:'PATCH',headers:{'content-type':'application/json','x-admin-key':key},body:JSON.stringify({action})});const result=await r.json();if(!r.ok)setError(result.error);else await load();setBusy('');}
  if(!items.length)return <form onSubmit={(e:FormEvent)=>{e.preventDefault();void load()}} className="mx-auto max-w-md rounded-xl border border-white/10 bg-[#111720] p-7"><h1 className="text-2xl font-black">Affiliate administration</h1><p className="mt-2 text-sm text-zinc-400">Enter the private admin key stored in Vercel.</p><input value={key} onChange={e=>setKey(e.target.value)} type="password" required className="mt-6 min-h-12 w-full rounded-md border border-white/10 bg-black/30 px-4 outline-none focus:border-ember"/><button className="mt-4 min-h-12 w-full rounded-md bg-ember font-black">Open applications</button>{error&&<p className="mt-4 text-sm text-red-300">{error}</p>}</form>;
  return <div><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-ember">Private workspace</p><h1 className="mt-2 text-3xl font-black">Affiliate applications</h1></div><button onClick={()=>load()} className="rounded-md border border-white/10 px-4 py-2 text-sm font-bold">Refresh</button></div>{error&&<p className="mt-5 text-red-300">{error}</p>}<div className="mt-8 grid gap-5">{items.map(a=><article key={a.id} className="rounded-xl border border-white/10 bg-[#111720] p-6"><div className="flex flex-wrap justify-between gap-4"><div><h2 className="text-xl font-black">{a.full_name}</h2><p className="mt-1 text-sm text-zinc-400">{a.email} · {a.primary_platform} · {a.audience_size}</p></div><span className="h-fit rounded-full border border-white/10 px-3 py-1 text-xs font-black uppercase">{a.status}</span></div><div className="mt-5 grid gap-4 text-sm md:grid-cols-2"><p><span className="text-zinc-500">Profile:</span> <a className="text-blue-300 underline" href={a.profile_url} target="_blank">Open channel</a></p><p><span className="text-zinc-500">Code:</span> <strong>{a.preferred_code}</strong></p><p><span className="text-zinc-500">TradingView:</span> {a.tradingview_username}</p><p><span className="text-zinc-500">Payout:</span> {a.payout_method} · {a.payout_handle}</p><p className="md:col-span-2"><span className="text-zinc-500">Plan:</span> {a.content_plan}</p></div><div className="mt-6 flex flex-wrap gap-3">{a.status==='pending'&&<button disabled={busy!==''} onClick={()=>act(a.id,'approve')} className="rounded-md bg-emerald-500 px-5 py-3 text-sm font-black text-black">Approve + create Stripe code</button>}{a.status!=='declined'&&<button disabled={busy!==''} onClick={()=>act(a.id,a.status==='approved'?'pause':'decline')} className="rounded-md border border-red-500/30 px-5 py-3 text-sm font-black text-red-200">{a.status==='approved'?'Pause code':'Decline'}</button>}</div></article>)}</div></div>;
}
